#!/usr/bin/env python3
"""Build a route-replay agent from a downloaded episode.

Why this exists. `scripts/rank_ladder.py` places our hand-written agent between
tier 5 and tier 6 of the reference ladder, and every rung above 5 runs the same
thing: a fixed production plan replayed turn by turn, with a thin repair layer on
top. The dataset NOTICE calls it "the shared public meta line" and reports finding
identical 712-turn farmer/hand sequences across 104 distinct teams in 530 public
replays. The current #1's published artifact is one 719-step action list plus WEED
repair plus SELL-slot reordering -- no planner, no scheduler, no opponent model.

So above ~$56k this is not a strategy competition, it is route selection. This
script turns a downloaded episode into a submittable agent of that shape, and
`--evaluate` scores candidate routes against the ladder so the route is chosen by
*measured* performance rather than by the cash it happened to bank in its original
episode. That distinction is the whole game: the best-banking route we have from
the 2026-08-05 field ($187,844) collapses to $392 when replayed, because it ran at
$8 cash on day 4 and cannot absorb a market that diverges.

    uv run python scripts/build_route_agent.py --list
    uv run python scripts/build_route_agent.py --evaluate 8 --episodes 4
    uv run python scripts/build_route_agent.py --replay <path> --seat 0 --out route_agent.py

Attribution. The three runtime layers -- bounded WEED repair, ordering already
existing SELL slots by price impact, and aligning the hands list to the live hand
count -- are the design published in
https://www.kaggle.com/code/kaitofukami/25-27-strict-future-v27-midgame-meta-reset
(Kaito Fukami), whose own route is credited to team Ezzzzzekki's public replay.
The implementation here is written from the environment's mechanics rather than
copied, and the route baked into any agent this script emits is whatever public
replay you point it at -- the generated file records its own provenance in a
header so the source episode, team and seat travel with the artifact.
"""

from __future__ import annotations

import argparse
import base64
import glob
import json
import os
import statistics
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(HERE)
sys.path.insert(0, PROJECT_ROOT)

LOG_DIR = os.path.join(PROJECT_ROOT, "logs")
DEFAULT_SOURCES = [
    os.path.join(LOG_DIR, "daily", "kaggriculture-episodes-2026-08-10"),
    os.path.join(LOG_DIR, "live_v0_1_0"),
    os.path.join(LOG_DIR, "live_v0_0_9"),
]

AGENT_TEMPLATE = '''"""Route-replay agent{provenance_line}

Generated by scripts/build_route_agent.py. Standard library only.

One recorded {n_steps}-step action route, replayed in both seats, plus three
runtime layers and nothing else -- no planner, no scheduler, no opponent model:

  * bounded WEED repair: a scripted PLANT/BUILD_* onto a tile that has become a
    WEED emits DIG instead, replays the intended action on the next step, then
    shifts the following steps of that unit's trace by one so the rest of the
    route stays aligned;
  * SELL-slot ordering: the SELL orders the route already contains are reordered
    among their own slots by price impact, so the largest price move happens while
    the market is still shallow and, against the 10-order-per-turn cap, the
    valuable sale is the one that survives. Nothing about production changes;
  * hands alignment: the hands list is padded or truncated to the live hand count,
    because a route recorded with N hands is otherwise invalid on a turn with M;
  * sell metering: SELL quantities for the metered products are held back to what
    still clears a price floor, but only while the farm already holds every dollar
    the rest of the route has to spend. Off unless `_METER_ITEMS` is non-empty.

Route provenance:{provenance_block}

Design credit for the three layers: Kaito Fukami,
https://www.kaggle.com/code/kaitofukami/25-27-strict-future-v27-midgame-meta-reset
"""

import base64
import json
import math
import zlib

AGENT_VERSION = "{version}"

# base85 of zlib of the JSON route. Chunked so `ruff format` is stable on the
# generated file -- one multi-kilobyte literal gets rewrapped on every run.
_ROUTE_B85_PARTS = [
{route_parts}]

_ROUTE = json.loads(zlib.decompress(base64.b85decode("".join(_ROUTE_B85_PARTS))))

_PRICE_FLOOR = 1.0
_MARKET_I0 = 10000
_MAX_MARKET_ORDERS = 10
_MARKET_PARAMS = {{
    "WHEAT": (25, 400, "sqrt", 0.80, "log", 0.20),
    "CARROT": (35, 450, "log", 0.20, "sqrt", 0.70),
    "TOMATO": (60, 200, "linear", 0.40, "sqrt", 0.60),
    "STRAWBERRY": (120, 100, "sqrt", 0.70, "linear", 1.60),
    "MELON": (250, 300, "log", 0.20, "sq", 3.60),
    "EGG": (50, 332, "linear", 0.40, "log", 0.20),
    "MILK": (160, 122, "sqrt", 0.60, "linear", 1.60),
    "WOOL": (200, 105, "log", 0.20, "sq", 3.20),
    "FERTILIZER": (100, 200, "linear", 0.40, "linear", 0.40),
}}

# Per-seat repair state. The env builds a fresh process per episode, but a seat
# can still be re-entered, so this resets whenever `step` goes backwards.
_REPAIR: dict = {{0: {{}}, 1: {{}}}}
_REPAIR_SHIFT_STEPS = 8

NO_OP = {{"farmer": ["PASS"], "hands": [], "market": []}}


def _get(obj, key, default=None):
    if isinstance(obj, dict):
        return obj.get(key, default)
    getter = getattr(obj, "get", None)
    if callable(getter):
        return getter(key, default)
    return getattr(obj, key, default)


def _seat(obs):
    return 1 if int(_get(obs, "player", 0) or 0) == 1 else 0


def _farm(obs, seat):
    farms = list(_get(obs, "farms", []) or [])
    return farms[seat] if seat < len(farms) else {{}}


def _step_index(obs, config):
    """Turn index. `step` is in the shared observation and is not guaranteed for
    every seat, so fall back to the per-seat clock; the env indexes turns as
    day * turnsPerDay + hour."""
    step = _get(obs, "step")
    if step is not None:
        return int(step)
    per_day = 24
    if config is not None:
        try:
            per_day = int(_get(config, "turnsPerDay", 24) or 24)
        except (TypeError, ValueError):
            per_day = 24
    return int(_get(obs, "day", 0) or 0) * per_day + int(_get(obs, "hour", 0) or 0)


def _copy_action(action):
    action = action or {{}}
    return {{
        "farmer": list(action.get("farmer") or ["PASS"]),
        "hands": [list(h or ["PASS"]) for h in (action.get("hands") or [])],
        "market": [list(o) for o in (action.get("market") or []) if o],
    }}


def _align_hands(action, obs):
    expected = len(_get(_farm(obs, _seat(obs)), "hands", []) or [])
    hands = list(action.get("hands") or [])
    if len(hands) < expected:
        hands.extend([["PASS"]] * (expected - len(hands)))
    action["hands"] = [list(h or ["PASS"]) for h in hands[:expected]]
    return action


def _route_at(step):
    if not _ROUTE:
        return {{}}
    return _ROUTE[min(max(int(step), 0), len(_ROUTE) - 1)] or {{}}


def _unit_from_route(step, slot):
    trace = _route_at(step)
    if slot == 0:
        return list(trace.get("farmer") or ["PASS"])
    hands = trace.get("hands") or []
    index = slot - 1
    return list(hands[index]) if index < len(hands) else ["PASS"]


def _tile_at(farm, position):
    try:
        return (_get(farm, "tiles", []) or [])[int(position[1])][int(position[0])]
    except (IndexError, TypeError, ValueError):
        return "LOCKED"


def _repair_weeds(obs, action, step):
    """DIG a weed that has appeared under a scripted build/plant, then resume.

    Weeds are the only per-episode randomness that can invalidate a route: a tile
    the route expects to be empty becomes a WEED and every PLANT on it silently
    no-ops for the rest of the game. Repair costs one turn and then replays the
    unit's own trace one step behind for a bounded window.
    """
    seat = _seat(obs)
    state = _REPAIR[seat]
    if step == 0 or step < state.get("last_step", -1):
        state = {{"last_step": step, "active": {{}}}}
        _REPAIR[seat] = state
    state["last_step"] = step

    farm = _farm(obs, seat)
    positions = [_get(farm, "farmer"), *list(_get(farm, "hands", []) or [])]
    units = [action.get("farmer") or ["PASS"], *list(action.get("hands") or [])]
    active = state["active"]

    for slot, entry in list(active.items()):
        if slot >= len(units):
            active.pop(slot, None)
            continue
        age = step - entry["start"]
        if age == 1:
            units[slot] = list(entry["intended"])
        elif 2 <= age <= 1 + _REPAIR_SHIFT_STEPS:
            units[slot] = _unit_from_route(step - 1, slot)
        else:
            active.pop(slot, None)

    for slot, (position, intended) in enumerate(zip(positions, units, strict=False)):
        if slot in active or not isinstance(intended, list) or not intended:
            continue
        if intended[0] not in ("PLANT", "BUILD_PASTURE", "BUILD_COOP"):
            continue
        tile = _tile_at(farm, position)
        if not (isinstance(tile, dict) and tile.get("kind") == "WEED"):
            continue
        active[slot] = {{"start": step, "intended": list(intended)}}
        units[slot] = ["DIG"]

    action["farmer"] = units[0] if units else ["PASS"]
    action["hands"] = units[1:]
    return action


def _shape(name, value):
    value = max(0.0, float(value))
    if name == "sq":
        return value * value
    if name == "sqrt":
        return math.sqrt(value)
    if name == "log":
        return math.log1p(value)
    if name == "log10":
        return math.log10(1.0 + value)
    return value


def _price_at(item, inventory):
    params = _MARKET_PARAMS.get(item)
    if params is None:
        return _PRICE_FLOOR
    base, scale, below_func, below_target, above_func, above_target = params
    if inventory < _MARKET_I0:
        amp = below_target * base / _shape(below_func, scale)
        price = base + amp * _shape(below_func, _MARKET_I0 - inventory)
    else:
        amp = above_target * base / _shape(above_func, scale)
        price = base - amp * _shape(above_func, inventory - _MARKET_I0)
    return max(_PRICE_FLOOR, round(price))


def _is_sell(order):
    return (
        isinstance(order, list)
        and len(order) >= 3
        and order[0] == "SELL"
        and order[1] in _MARKET_PARAMS
    )


def _impact(obs, order):
    """How much this order moves its own price, times its size."""
    try:
        quantity = max(0, int(order[2]))
    except (TypeError, ValueError):
        return 0.0
    item = str(order[1])
    market = _get(obs, "market", {{}}) or {{}}
    inventory = int(_get(_get(market, "inventory", {{}}) or {{}}, item, _MARKET_I0) or _MARKET_I0)
    now = _price_at(item, inventory)
    after = _price_at(item, inventory + quantity)
    return float(quantity) * max(0.0, now - after)


def _rank_sells(obs, action):
    """Reorder SELL orders among the slots they already occupy. Sizes, items and
    every non-SELL order stay exactly where the route put them."""
    market = list(action.get("market") or [])
    sells = [(i, o) for i, o in enumerate(market) if _is_sell(o)]
    if len(sells) < 2:
        return action
    ranked = sorted(sells, key=lambda pair: (-_impact(obs, pair[1]), pair[0]))
    order_iter = iter(o for _, o in ranked)
    action["market"] = [next(order_iter) if _is_sell(o) else o for o in market]
    return action


# ---------------------------------------------------------------------------
# Sell metering inside the route's own cash envelope (issue #30).
#
# The route is a cash schedule, not a production plan with a market layer on top.
# Every HIRE and BUY is timed against money it expects to already have, and
# `_do_hire` returns without a word when it cannot afford the hire, so a withheld
# sale does not cost a price -- it costs a hand, and then the throughput that hand
# was going to produce. Flat price floors were measured on exactly this route and
# they are catastrophic: $26,322 / $23,345 / $1,090 at floors 0.60 / 0.85 / 1.00
# against a $104,027 baseline (docs/experiments.md, issue #23).
#
# What makes deferral safe is that the route is known in advance, so the cash it
# still has to find is computable rather than guessable. `_CASH_FIXED[t]` is the
# exact cost of every HIRE / BUY_SEED / BUY_ANIMAL / BUY_LAND at steps >= t --
# HIRE is `fib(hires so far today)` and the counter resets at the day boundary,
# BUY_LAND walks a fixed ladder, seeds and animals are catalogue prices --  and
# `_CASH_UNITS[t]` counts the BUY_PRODUCT units still to come, which are priced
# from the live market because their cost is not knowable offline. Money only
# ever leaves the farm through those orders, so
#
#     money(u) >= money(t) - spent(t..u) >= need(t) - spent(t..u) = need(u)
#
# for every u >= t: hold `need(t)` and no future order in the route can fail.
# Metering runs only while that inequality holds, which is the whole difference
# between this layer and the three attempts that came before it.
# ---------------------------------------------------------------------------

_SEED_COST = {{"WHEAT": 10, "CARROT": 20, "TOMATO": 50, "STRAWBERRY": 100, "MELON": 80}}
_ANIMAL_COST = {{"GOOSE": 300, "COW": 400, "SHEEP": 500}}
_LAND_PRICES = (1000, 2000, 4000)
_TURNS_PER_DAY = 24

# Metering knobs. `_METER_ITEMS = ()` disables the layer outright and is the OFF
# arm of every A/B in docs/experiments.md -- the same file, one tuple emptied.
_METER_ITEMS = ()
_METER_FLOOR = 0.55  # sell while the unit still clears this fraction of base
_METER_MAX_HOLD = 24  # shed slots we are ever willing to tie up
_METER_SHED_RELEASE = 78  # observed shed occupancy that ends all withholding
_METER_FLUSH_STEP = 672  # last two days: a held unit at the horn scores $0
_METER_BUY_MARGIN = 1.25  # safety multiple on the unpriced BUY_PRODUCT tail

_METER_STATE: dict = {{0: {{}}, 1: {{}}}}


def _fib(n):
    """`_fib(0) = 1, _fib(1) = 1, _fib(2) = 2, ...`, the interpreter's indexing."""
    a, b = 1, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def _cash_requirement(route):
    """(fixed, units) cumulative over steps >= t. See search/cash_schedule.py."""
    n = len(route)
    per_fixed = [0.0] * n
    per_units = [0] * n
    hires_today = 0
    day = -1
    lands = 0
    for t, action in enumerate(route):
        if t // _TURNS_PER_DAY != day:
            day = t // _TURNS_PER_DAY
            hires_today = 0
        for order in action.get("market") or []:
            if not isinstance(order, list) or not order:
                continue
            op = order[0]
            if op == "HIRE":
                per_fixed[t] += _fib(hires_today)
                hires_today += 1
            elif op == "BUY_LAND":
                if lands < len(_LAND_PRICES):
                    per_fixed[t] += _LAND_PRICES[lands]
                    lands += 1
            elif op in ("BUY_SEED", "BUY_ANIMAL", "BUY_PRODUCT") and len(order) >= 3:
                try:
                    qty = int(order[2])
                except (TypeError, ValueError):
                    continue
                if qty <= 0:
                    continue
                if op == "BUY_SEED":
                    per_fixed[t] += _SEED_COST.get(order[1], 0) * qty
                elif op == "BUY_ANIMAL":
                    per_fixed[t] += _ANIMAL_COST.get(order[1], 0) * qty
                else:
                    per_units[t] += qty
    fixed = [0.0] * (n + 1)
    units = [0] * (n + 1)
    for t in range(n - 1, -1, -1):
        fixed[t] = fixed[t + 1] + per_fixed[t]
        units[t] = units[t + 1] + per_units[t]
    return fixed, units


_CASH_FIXED, _CASH_UNITS = _cash_requirement(_ROUTE)


def _cash_needed(step, wheat_price):
    """What the rest of the route still has to pay, from `step` on."""
    idx = min(max(int(step), 0), len(_CASH_FIXED) - 1)
    return _CASH_FIXED[idx] + _CASH_UNITS[idx] * wheat_price * _METER_BUY_MARGIN


def _sellable_above(item, inventory, limit):
    """How many of the next `limit` units still clear at or above the floor."""
    params = _MARKET_PARAMS.get(item)
    if params is None:
        return limit
    floor = _METER_FLOOR * params[0]
    n = 0
    while n < limit and _price_at(item, inventory + n) >= floor:
        n += 1
    return n


def _meter_state(obs, step):
    seat = _seat(obs)
    state = _METER_STATE[seat]
    if step == 0 or step < state.get("last_step", -1):
        state = {{"held": {{}}}}
        _METER_STATE[seat] = state
    state.setdefault("held", {{}})
    state["last_step"] = step
    return state


def _meter_sells(obs, action, step):
    """Withhold units that would clear below the floor, inside the cash envelope.

    Three releases end withholding, because unsold stock scores $0 and the shed
    is the binding constraint -- this route already peaks at 100/100:

      * **solvency** -- `money < _cash_needed(step)` hands the schedule straight
        back to the route. This is the envelope, and it is the only reason this
        is not #23's deferral experiment run a fourth time.
      * **shed pressure** -- `obs.private.shed` predates this turn's PLACE and
        the end-of-day drop, so it is a *lower* bound; the threshold sits well
        under `shedCapacity` and everything held goes the moment it trips.
      * **endgame** -- from `_METER_FLUSH_STEP` on, everything goes at whatever
        the market pays.

    Held quantities are notional: the route already asks to sell more MILK than
    the shed holds, so a withheld unit may never have existed. That only ever
    costs a wasted order slot, never a sale, because the interpreter drops a SELL
    it cannot fill and the layer only ever appends into free slots.
    """
    if not _METER_ITEMS:
        return action
    orders = list(action.get("market") or [])
    state = _meter_state(obs, step)
    held = state["held"]
    if not orders and not held:
        return action

    farm = _farm(obs, _seat(obs))
    inventory = dict(_get(_get(obs, "market", {{}}) or {{}}, "inventory", {{}}) or {{}})
    shed = _get(_get(obs, "private", {{}}) or {{}}, "shed", {{}}) or {{}}

    wheat = _price_at("WHEAT", int(inventory.get("WHEAT", _MARKET_I0) or _MARKET_I0))
    money = float(_get(farm, "money", 0.0) or 0.0)
    occupancy = sum(v for v in shed.values() if isinstance(v, int))
    release = (
        money < _cash_needed(step, wheat)
        or step >= _METER_FLUSH_STEP
        or occupancy >= _METER_SHED_RELEASE
    )

    out = []
    for order in orders:
        if not (_is_sell(order) and order[1] in _METER_ITEMS):
            out.append(order)
            continue
        item = order[1]
        try:
            qty = max(0, int(order[2]))
        except (TypeError, ValueError):
            out.append(order)
            continue
        inv = int(inventory.get(item, _MARKET_I0) or _MARKET_I0)
        if release:
            qty += held.pop(item, 0)
        else:
            room = max(0, _METER_MAX_HOLD - sum(held.values()))
            withhold = min(qty - _sellable_above(item, inv, qty), room)
            if withhold > 0:
                held[item] = held.get(item, 0) + withhold
                qty -= withhold
        if qty <= 0:
            continue
        inventory[item] = inv + qty
        out.append([order[0], item, qty])

    # Drain the backlog on the turns the route is not already selling it: into
    # the floor once the town's drain has lifted the price back, all at once on
    # a release. Appended only into slots the route left free, so nothing the
    # interpreter would have processed is pushed past `maxMarketOrdersPerTurn`.
    for item in _METER_ITEMS:
        n = held.get(item, 0)
        if n <= 0 or len(out) >= _MAX_MARKET_ORDERS:
            continue
        inv = int(inventory.get(item, _MARKET_I0) or _MARKET_I0)
        take = n if release else _sellable_above(item, inv, n)
        if take <= 0:
            continue
        held[item] = n - take
        inventory[item] = inv + take
        out.append(["SELL", item, take])

    action["market"] = out
    return action


def agent(obs, config=None):
    try:
        step = _step_index(obs, config)
        action = _copy_action(_route_at(step))
        action = _repair_weeds(obs, action, step)
        action = _meter_sells(obs, action, step)
        action = _rank_sells(obs, action)
        return _align_hands(action, obs)
    except Exception:
        try:
            hands = len(_get(_farm(obs, _seat(obs)), "hands", []) or [])
        except Exception:
            hands = 0
        return {{"farmer": ["PASS"], "hands": [["PASS"]] * hands, "market": []}}
'''


def iter_episodes(sources):
    out = []
    for src in sources:
        if os.path.isfile(src):
            out.append(src)
        elif os.path.isdir(src):
            out.extend(sorted(glob.glob(os.path.join(src, "*.json"))))
    return out


def load_episode(path):
    try:
        with open(path, "rb") as f:
            head = f.read(65536)
            if b'"kaggriculture"' not in head:
                return None
            data = json.loads(head + f.read())
    except (OSError, ValueError):
        return None
    return data if data.get("steps") else None


def extract_route(data, seat):
    """The seat's action at each step.

    `steps[t]["action"]` is the action that PRODUCED `steps[t]`, and `steps[0]`'s
    action is empty for every seat, so the action taken while looking at the state
    recorded at index t is the one stored at index t + 1.
    """
    steps = data["steps"]
    route = []
    for t in range(1, len(steps)):
        entry = steps[t][seat] if seat < len(steps[t]) else {}
        action = (entry or {}).get("action")
        if not isinstance(action, dict):
            action = {}
        route.append(
            {
                "farmer": list(action.get("farmer") or ["PASS"]),
                "hands": [list(h or ["PASS"]) for h in (action.get("hands") or [])],
                "market": [list(o) for o in (action.get("market") or []) if o],
            }
        )
    return route


def candidates(sources, limit=None):
    rows = []
    for path in iter_episodes(sources):
        data = load_episode(path)
        if not data:
            continue
        rewards = data.get("rewards") or []
        if len(rewards) < 2:
            continue
        seat = 0 if float(rewards[0] or 0) >= float(rewards[1] or 0) else 1
        teams = (data.get("info") or {}).get("TeamNames") or ["?", "?"]
        rows.append(
            {
                "cash": float(rewards[seat] or 0),
                "path": path,
                "seat": seat,
                "team": str(teams[seat] if seat < len(teams) else "?").strip('"'),
                "episode": (data.get("info") or {}).get("EpisodeId") or data.get("id"),
            }
        )
    rows.sort(key=lambda r: -r["cash"])
    return rows[:limit] if limit else rows


def emit_agent(data, seat, out_path, version="route-1"):
    route = extract_route(data, seat)
    payload = json.dumps(route, separators=(",", ":")).encode("utf-8")
    blob = base64.b85encode(zlib.compress(payload, 9)).decode("ascii")
    # The b85 alphabet has no quote or backslash, so chunks embed verbatim.
    parts = "".join(f'    "{blob[i : i + 92]}",\n' for i in range(0, len(blob), 92))

    info = data.get("info") or {}
    teams = info.get("TeamNames") or ["?", "?"]
    rewards = data.get("rewards") or [0, 0]
    provenance = {
        "episode": info.get("EpisodeId") or data.get("id"),
        "seat": seat,
        "team": str(teams[seat] if seat < len(teams) else "?").strip('"'),
        "recorded_cash": float(rewards[seat] or 0),
        "steps": len(route),
    }
    block = "".join(f"\n  {k}: {v}" for k, v in provenance.items())
    source = AGENT_TEMPLATE.format(
        provenance_line=f" -- {provenance['team']} episode {provenance['episode']} seat {seat}.",
        provenance_block=block,
        n_steps=len(route),
        route_parts=parts,
        version=version,
    )
    with open(out_path, "w") as f:
        f.write(source)
    return provenance, len(source)


def evaluate(agent_path, tiers, episodes, seed):
    """Rank one generated agent against the ladder; returns (wins, games, margin)."""
    sys.path.insert(0, HERE)
    import rank_ladder

    rows = []
    for tier, slug, _headline in rank_ladder.RUNGS:
        if tier not in tiers:
            continue
        opponent = rank_ladder.resolve_rung(slug)
        if opponent is None:
            continue
        for i in range(episodes):
            rows.append(rank_ladder.play(agent_path, opponent, seed + i, bool(i % 2), 720))
    if not rows:
        return 0, 0, 0.0
    wins = sum(1 for r in rows if r["me"] > r["opp"])
    margin = statistics.mean(r["me"] - r["opp"] for r in rows)
    return wins, len(rows), margin


def main():
    parser = argparse.ArgumentParser(description="Build a route-replay agent from a replay.")
    parser.add_argument("--replay", help="episode JSON to bake")
    parser.add_argument("--seat", type=int, default=None, help="seat to bake (default: the winner)")
    parser.add_argument("--out", default="route_agent.py")
    parser.add_argument("--sources", nargs="*", default=DEFAULT_SOURCES)
    parser.add_argument(
        "--list", action="store_true", help="rank candidate routes by recorded cash"
    )
    parser.add_argument(
        "--evaluate", type=int, default=0, metavar="N", help="bake and rank the top N candidates"
    )
    parser.add_argument("--tiers", default="4,5,6", help="ladder tiers for --evaluate")
    parser.add_argument("--episodes", type=int, default=4, help="episodes per tier for --evaluate")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    if args.list or args.evaluate:
        rows = candidates(args.sources, limit=max(args.evaluate, 20) if args.evaluate else 25)
        if args.list:
            print(f"{'cash':>10}  {'seat':>4}  team / episode")
            for r in rows:
                print(f"{r['cash']:>10,.0f}  {r['seat']:>4}  {r['team'][:24]:<24} {r['episode']}")
            return

        sys.path.insert(0, HERE)
        import rank_ladder

        tiers = rank_ladder.parse_tiers(args.tiers)
        print(
            f"baking and ranking the top {args.evaluate} routes against tiers "
            f"{sorted(tiers)}, {args.episodes} episodes each\n"
        )
        results = []
        work = os.path.join(LOG_DIR, "_routes")
        os.makedirs(work, exist_ok=True)
        for rank, row in enumerate(rows[: args.evaluate], 1):
            data = load_episode(row["path"])
            if not data:
                continue
            path = os.path.join(work, f"route_{row['episode']}_{row['seat']}.py")
            prov, size = emit_agent(data, row["seat"], path, version=f"route-{row['episode']}")
            wins, games, margin = evaluate(path, tiers, args.episodes, args.seed)
            results.append((wins, margin, row, path, size))
            print(
                f"  [{rank}/{args.evaluate}] {row['team'][:20]:<20} ep {row['episode']} "
                f"seat {row['seat']}  recorded ${row['cash']:>9,.0f}  "
                f"-> ladder {wins}/{games}  margin ${margin:>+10,.0f}  ({size:,} bytes)"
            )
        if results:
            results.sort(key=lambda r: (-r[0], -r[1]))
            best = results[0]
            print(
                f"\nBEST: {best[2]['team']} episode {best[2]['episode']} seat {best[2]['seat']} "
                f"-> {best[0]} ladder wins, margin ${best[1]:+,.0f}\n  {best[3]}"
            )
        return

    if not args.replay:
        raise SystemExit("need --replay, --list or --evaluate")
    data = load_episode(args.replay)
    if not data:
        raise SystemExit(f"not a kaggriculture replay: {args.replay}")
    seat = args.seat
    if seat is None:
        rewards = data.get("rewards") or [0, 0]
        seat = 0 if float(rewards[0] or 0) >= float(rewards[1] or 0) else 1
    prov, size = emit_agent(data, seat, args.out)
    print(f"wrote {args.out} ({size:,} bytes)")
    for key, value in prov.items():
        print(f"  {key}: {value}")


if __name__ == "__main__":
    main()
