#!/usr/bin/env python3
"""Build a route-replay agent from a downloaded episode.

Why this exists. `scripts/rank_ladder.py` places our hand-written agent between
tier 5 and tier 6 of the reference ladder, and every rung above 5 runs the same
thing: a fixed production plan replayed turn by turn, with a thin repair layer on
top. The dataset NOTICE calls it "the shared public meta line" and reports finding
identical 712-turn farmer/hand sequences across 104 distinct teams in 530 public
replays. The current #1's published artifact is one 719-step action list plus WEED
repair plus SELL-slot reordering -- no planner, no scheduler, no opponent model.

So above ~$56k this is not a strategy competition, it is route selection. This
script turns a downloaded episode into a submittable agent of that shape, and
`--evaluate` scores candidate routes against the ladder so the route is chosen by
*measured* performance rather than by the cash it happened to bank in its original
episode. That distinction is the whole game: the best-banking route we have from
the 2026-08-05 field ($187,844) collapses to $392 when replayed, because it ran at
$8 cash on day 4 and cannot absorb a market that diverges.

    uv run python scripts/build_route_agent.py --list
    uv run python scripts/build_route_agent.py --evaluate 8 --episodes 4
    uv run python scripts/build_route_agent.py --replay <path> --seat 0 --out route_agent.py

Attribution. The three runtime layers -- bounded WEED repair, ordering already
existing SELL slots by price impact, and aligning the hands list to the live hand
count -- are the design published in
https://www.kaggle.com/code/kaitofukami/25-27-strict-future-v27-midgame-meta-reset
(Kaito Fukami), whose own route is credited to team Ezzzzzekki's public replay.
The implementation here is written from the environment's mechanics rather than
copied, and the route baked into any agent this script emits is whatever public
replay you point it at -- the generated file records its own provenance in a
header so the source episode, team and seat travel with the artifact.
"""

from __future__ import annotations

import argparse
import base64
import glob
import json
import os
import statistics
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(HERE)
sys.path.insert(0, PROJECT_ROOT)

LOG_DIR = os.path.join(PROJECT_ROOT, "logs")
DEFAULT_SOURCES = [
    os.path.join(LOG_DIR, "daily", "kaggriculture-episodes-2026-08-10"),
    os.path.join(LOG_DIR, "live_v0_1_0"),
    os.path.join(LOG_DIR, "live_v0_0_9"),
]

AGENT_TEMPLATE = '''"""Route-replay agent{provenance_line}

Generated by scripts/build_route_agent.py. Standard library only.

One recorded {n_steps}-step action route, replayed in both seats, plus three
runtime layers and nothing else -- no planner, no scheduler, no opponent model:

  * bounded WEED repair: a scripted PLANT/BUILD_* onto a tile that has become a
    WEED emits DIG instead, replays the intended action on the next step, then
    shifts the following steps of that unit's trace by one so the rest of the
    route stays aligned;
  * SELL-slot ordering: the SELL orders the route already contains are reordered
    among their own slots by price impact, so the largest price move happens while
    the market is still shallow and, against the 10-order-per-turn cap, the
    valuable sale is the one that survives. Nothing about production changes;
  * hands alignment: the hands list is padded or truncated to the live hand count,
    because a route recorded with N hands is otherwise invalid on a turn with M.

Route provenance:{provenance_block}

Design credit for the three layers: Kaito Fukami,
https://www.kaggle.com/code/kaitofukami/25-27-strict-future-v27-midgame-meta-reset
"""

import base64
import json
import math
import zlib

AGENT_VERSION = "{version}"

# base85 of zlib of the JSON route. Chunked so `ruff format` is stable on the
# generated file -- one multi-kilobyte literal gets rewrapped on every run.
_ROUTE_B85_PARTS = [
{route_parts}]

_ROUTE = json.loads(zlib.decompress(base64.b85decode("".join(_ROUTE_B85_PARTS))))

_PRICE_FLOOR = 1.0
_MARKET_I0 = 10000
_MARKET_PARAMS = {{
    "WHEAT": (25, 400, "sqrt", 0.80, "log", 0.20),
    "CARROT": (35, 450, "log", 0.20, "sqrt", 0.70),
    "TOMATO": (60, 200, "linear", 0.40, "sqrt", 0.60),
    "STRAWBERRY": (120, 100, "sqrt", 0.70, "linear", 1.60),
    "MELON": (250, 300, "log", 0.20, "sq", 3.60),
    "EGG": (50, 332, "linear", 0.40, "log", 0.20),
    "MILK": (160, 122, "sqrt", 0.60, "linear", 1.60),
    "WOOL": (200, 105, "log", 0.20, "sq", 3.20),
    "FERTILIZER": (100, 200, "linear", 0.40, "linear", 0.40),
}}

def _is_sell(order):
    return (
        isinstance(order, list)
        and len(order) >= 3
        and order[0] == "SELL"
        and order[1] in _MARKET_PARAMS
    )

_SELL_SUFFIX_SUMS: list[dict[str, int]] = [{{}} for _ in range(len(_ROUTE))]
_current_sums: dict[str, int] = {{}}
for _t in range(len(_ROUTE) - 1, -1, -1):
    for _order in _ROUTE[_t].get("market") or []:
        if _is_sell(_order) and _order[1] != "WHEAT":
            try:
                _qty = max(0, int(_order[2]))
                _current_sums[_order[1]] = _current_sums.get(_order[1], 0) + _qty
            except (ValueError, TypeError):
                pass
    _SELL_SUFFIX_SUMS[_t] = dict(_current_sums)

# Per-seat repair state. The env builds a fresh process per episode, but a seat
# can still be re-entered, so this resets whenever `step` goes backwards.
_REPAIR: dict = {{0: {{}}, 1: {{}}}}
_REPAIR_SHIFT_STEPS = 8

NO_OP = {{"farmer": ["PASS"], "hands": [], "market": []}}


def _get(obj, key, default=None):
    if isinstance(obj, dict):
        return obj.get(key, default)
    getter = getattr(obj, "get", None)
    if callable(getter):
        return getter(key, default)
    return getattr(obj, key, default)


def _seat(obs):
    return 1 if int(_get(obs, "player", 0) or 0) == 1 else 0


def _farm(obs, seat):
    farms = list(_get(obs, "farms", []) or [])
    return farms[seat] if seat < len(farms) else {{}}


def _step_index(obs, config):
    """Turn index. `step` is in the shared observation and is not guaranteed for
    every seat, so fall back to the per-seat clock; the env indexes turns as
    day * turnsPerDay + hour."""
    step = _get(obs, "step")
    if step is not None:
        return int(step)
    per_day = 24
    if config is not None:
        try:
            per_day = int(_get(config, "turnsPerDay", 24) or 24)
        except (TypeError, ValueError):
            per_day = 24
    return int(_get(obs, "day", 0) or 0) * per_day + int(_get(obs, "hour", 0) or 0)


def _copy_action(action):
    action = action or {{}}
    return {{
        "farmer": list(action.get("farmer") or ["PASS"]),
        "hands": [list(h or ["PASS"]) for h in (action.get("hands") or [])],
        "market": [list(o) for o in (action.get("market") or []) if o],
    }}


def _align_hands(action, obs):
    expected = len(_get(_farm(obs, _seat(obs)), "hands", []) or [])
    hands = list(action.get("hands") or [])
    if len(hands) < expected:
        hands.extend([["PASS"]] * (expected - len(hands)))
    action["hands"] = [list(h or ["PASS"]) for h in hands[:expected]]
    return action


def _route_at(step):
    if not _ROUTE:
        return {{}}
    return _ROUTE[min(max(int(step), 0), len(_ROUTE) - 1)] or {{}}


def _unit_from_route(step, slot):
    trace = _route_at(step)
    if slot == 0:
        return list(trace.get("farmer") or ["PASS"])
    hands = trace.get("hands") or []
    index = slot - 1
    return list(hands[index]) if index < len(hands) else ["PASS"]


def _tile_at(farm, position):
    try:
        return (_get(farm, "tiles", []) or [])[int(position[1])][int(position[0])]
    except (IndexError, TypeError, ValueError):
        return "LOCKED"


def _repair_weeds(obs, action, step):
    """DIG a weed that has appeared under a scripted build/plant, then resume.

    Weeds are the only per-episode randomness that can invalidate a route: a tile
    the route expects to be empty becomes a WEED and every PLANT on it silently
    no-ops for the rest of the game. Repair costs one turn and then replays the
    unit's own trace one step behind for a bounded window.
    """
    seat = _seat(obs)
    state = _REPAIR[seat]
    if step == 0 or step < state.get("last_step", -1):
        state = {{"last_step": step, "active": {{}}}}
        _REPAIR[seat] = state
    state["last_step"] = step

    farm = _farm(obs, seat)
    positions = [_get(farm, "farmer"), *list(_get(farm, "hands", []) or [])]
    units = [action.get("farmer") or ["PASS"], *list(action.get("hands") or [])]
    active = state["active"]

    for slot, entry in list(active.items()):
        if slot >= len(units):
            active.pop(slot, None)
            continue
        age = step - entry["start"]
        if age == 1:
            units[slot] = list(entry["intended"])
        elif 2 <= age <= 1 + _REPAIR_SHIFT_STEPS:
            units[slot] = _unit_from_route(step - 1, slot)
        else:
            active.pop(slot, None)

    for slot, (position, intended) in enumerate(zip(positions, units, strict=False)):
        if slot in active or not isinstance(intended, list) or not intended:
            continue
        if intended[0] not in ("PLANT", "BUILD_PASTURE", "BUILD_COOP"):
            continue
        tile = _tile_at(farm, position)
        if not (isinstance(tile, dict) and tile.get("kind") == "WEED"):
            continue
        active[slot] = {{"start": step, "intended": list(intended)}}
        units[slot] = ["DIG"]

    action["farmer"] = units[0] if units else ["PASS"]
    action["hands"] = units[1:]
    return action


def _shape(name, value):
    value = max(0.0, float(value))
    if name == "sq":
        return value * value
    if name == "sqrt":
        return math.sqrt(value)
    if name == "log":
        return math.log1p(value)
    if name == "log10":
        return math.log10(1.0 + value)
    return value


def _price_at(item, inventory):
    params = _MARKET_PARAMS.get(item)
    if params is None:
        return _PRICE_FLOOR
    base, scale, below_func, below_target, above_func, above_target = params
    if inventory < _MARKET_I0:
        amp = below_target * base / _shape(below_func, scale)
        price = base + amp * _shape(below_func, _MARKET_I0 - inventory)
    else:
        amp = above_target * base / _shape(above_func, scale)
        price = base - amp * _shape(above_func, inventory - _MARKET_I0)
    return max(_PRICE_FLOOR, round(price))


def _impact(obs, order):
    """How much this order moves its own price, times its size."""
    try:
        quantity = max(0, int(order[2]))
    except (TypeError, ValueError):
        return 0.0
    item = str(order[1])
    market = _get(obs, "market", {{}}) or {{}}
    inventory = int(_get(_get(market, "inventory", {{}}) or {{}}, item, _MARKET_I0) or _MARKET_I0)
    now = _price_at(item, inventory)
    after = _price_at(item, inventory + quantity)
    return float(quantity) * max(0.0, now - after)


def _accelerate_sells(obs, action, step):
    """Sell acceleration and ranking: sell products currently in the shed if they
    are scheduled to be sold later, up to the route's remaining budget for them.
    Ranks all SELL orders by price impact and preserves all non-SELL slots."""
    market = list(action.get("market") or [])
    shed = _get(_get(obs, "private", {{}}) or {{}}, "shed", {{}}) or {{}}

    new_market = [None] * len(market)
    route_sells = {{}}

    for i, order in enumerate(market):
        if _is_sell(order):
            item = order[1]
            try:
                qty = max(0, int(order[2]))
                route_sells[item] = route_sells.get(item, 0) + qty
            except (ValueError, TypeError):
                pass
        else:
            new_market[i] = order

    budget = _SELL_SUFFIX_SUMS[step] if step < len(_SELL_SUFFIX_SUMS) else {{}}
    sells_to_place = []

    items = set(route_sells.keys())
    for item, qty_in_shed in shed.items():
        if item != "WHEAT" and item in budget and qty_in_shed > 0:
            items.add(item)

    for item in items:
        route_qty = route_sells.get(item, 0)
        shed_qty = int(shed.get(item, 0) or 0)
        max_budget = budget.get(item, 0)
        accelerated = min(shed_qty, max_budget) if item != "WHEAT" else 0
        final_qty = max(route_qty, accelerated)

        if final_qty > 0:
            sells_to_place.append(["SELL", item, final_qty])

    if not sells_to_place and len(market) == len(action.get("market") or []):
        return action

    sells_to_place.sort(key=lambda order: (-_impact(obs, order), order[1]))

    sell_idx = 0
    for i in range(len(new_market)):
        if new_market[i] is None:
            if sell_idx < len(sells_to_place):
                # pyrefly: ignore [unsupported-operation]
                new_market[i] = sells_to_place[sell_idx]
                sell_idx += 1

    final_market = [o for o in new_market if o is not None]

    while sell_idx < len(sells_to_place) and len(final_market) < 10:
        # pyrefly: ignore [bad-argument-type]
        final_market.append(sells_to_place[sell_idx])
        sell_idx += 1

    action["market"] = final_market
    return action


def agent(obs, config=None):
    try:
        step = _step_index(obs, config)
        action = _copy_action(_route_at(step))
        action = _repair_weeds(obs, action, step)
        action = _accelerate_sells(obs, action, step)
        return _align_hands(action, obs)
    except Exception:
        try:
            hands = len(_get(_farm(obs, _seat(obs)), "hands", []) or [])
        except Exception:
            hands = 0
        return {{"farmer": ["PASS"], "hands": [["PASS"]] * hands, "market": []}}
'''


def iter_episodes(sources):
    out = []
    for src in sources:
        if os.path.isfile(src):
            out.append(src)
        elif os.path.isdir(src):
            out.extend(sorted(glob.glob(os.path.join(src, "*.json"))))
    return out


def load_episode(path):
    try:
        with open(path, "rb") as f:
            head = f.read(65536)
            if b'"kaggriculture"' not in head:
                return None
            data = json.loads(head + f.read())
    except (OSError, ValueError):
        return None
    return data if data.get("steps") else None


def extract_route(data, seat):
    """The seat's action at each step.

    `steps[t]["action"]` is the action that PRODUCED `steps[t]`, and `steps[0]`'s
    action is empty for every seat, so the action taken while looking at the state
    recorded at index t is the one stored at index t + 1.
    """
    steps = data["steps"]
    route = []
    for t in range(1, len(steps)):
        entry = steps[t][seat] if seat < len(steps[t]) else {}
        action = (entry or {}).get("action")
        if not isinstance(action, dict):
            action = {}
        route.append(
            {
                "farmer": list(action.get("farmer") or ["PASS"]),
                "hands": [list(h or ["PASS"]) for h in (action.get("hands") or [])],
                "market": [list(o) for o in (action.get("market") or []) if o],
            }
        )
    return route


def candidates(sources, limit=None):
    rows = []
    for path in iter_episodes(sources):
        data = load_episode(path)
        if not data:
            continue
        rewards = data.get("rewards") or []
        if len(rewards) < 2:
            continue
        seat = 0 if float(rewards[0] or 0) >= float(rewards[1] or 0) else 1
        teams = (data.get("info") or {}).get("TeamNames") or ["?", "?"]
        rows.append(
            {
                "cash": float(rewards[seat] or 0),
                "path": path,
                "seat": seat,
                "team": str(teams[seat] if seat < len(teams) else "?").strip('"'),
                "episode": (data.get("info") or {}).get("EpisodeId") or data.get("id"),
            }
        )
    rows.sort(key=lambda r: -r["cash"])
    return rows[:limit] if limit else rows


def emit_agent(data, seat, out_path, version="route-1"):
    route = extract_route(data, seat)
    payload = json.dumps(route, separators=(",", ":")).encode("utf-8")
    blob = base64.b85encode(zlib.compress(payload, 9)).decode("ascii")
    # The b85 alphabet has no quote or backslash, so chunks embed verbatim.
    parts = "".join(f'    "{blob[i : i + 92]}",\n' for i in range(0, len(blob), 92))

    info = data.get("info") or {}
    teams = info.get("TeamNames") or ["?", "?"]
    rewards = data.get("rewards") or [0, 0]
    provenance = {
        "episode": info.get("EpisodeId") or data.get("id"),
        "seat": seat,
        "team": str(teams[seat] if seat < len(teams) else "?").strip('"'),
        "recorded_cash": float(rewards[seat] or 0),
        "steps": len(route),
    }
    block = "".join(f"\n  {k}: {v}" for k, v in provenance.items())
    source = AGENT_TEMPLATE.format(
        provenance_line=f" -- {provenance['team']} episode {provenance['episode']} seat {seat}.",
        provenance_block=block,
        n_steps=len(route),
        route_parts=parts,
        version=version,
    )
    with open(out_path, "w") as f:
        f.write(source)
    return provenance, len(source)


def evaluate(agent_path, tiers, episodes, seed):
    """Rank one generated agent against the ladder; returns (wins, games, margin)."""
    sys.path.insert(0, HERE)
    import rank_ladder

    rows = []
    for tier, slug, _headline in rank_ladder.RUNGS:
        if tier not in tiers:
            continue
        opponent = rank_ladder.resolve_rung(slug)
        if opponent is None:
            continue
        for i in range(episodes):
            rows.append(rank_ladder.play(agent_path, opponent, seed + i, bool(i % 2), 720))
    if not rows:
        return 0, 0, 0.0
    wins = sum(1 for r in rows if r["me"] > r["opp"])
    margin = statistics.mean(r["me"] - r["opp"] for r in rows)
    return wins, len(rows), margin


def main():
    parser = argparse.ArgumentParser(description="Build a route-replay agent from a replay.")
    parser.add_argument("--replay", help="episode JSON to bake")
    parser.add_argument("--seat", type=int, default=None, help="seat to bake (default: the winner)")
    parser.add_argument("--out", default="route_agent.py")
    parser.add_argument("--sources", nargs="*", default=DEFAULT_SOURCES)
    parser.add_argument(
        "--list", action="store_true", help="rank candidate routes by recorded cash"
    )
    parser.add_argument(
        "--evaluate", type=int, default=0, metavar="N", help="bake and rank the top N candidates"
    )
    parser.add_argument("--tiers", default="4,5,6", help="ladder tiers for --evaluate")
    parser.add_argument("--episodes", type=int, default=4, help="episodes per tier for --evaluate")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    if args.list or args.evaluate:
        rows = candidates(args.sources, limit=max(args.evaluate, 20) if args.evaluate else 25)
        if args.list:
            print(f"{'cash':>10}  {'seat':>4}  team / episode")
            for r in rows:
                print(f"{r['cash']:>10,.0f}  {r['seat']:>4}  {r['team'][:24]:<24} {r['episode']}")
            return

        sys.path.insert(0, HERE)
        import rank_ladder

        tiers = rank_ladder.parse_tiers(args.tiers)
        print(
            f"baking and ranking the top {args.evaluate} routes against tiers "
            f"{sorted(tiers)}, {args.episodes} episodes each\n"
        )
        results = []
        work = os.path.join(LOG_DIR, "_routes")
        os.makedirs(work, exist_ok=True)
        for rank, row in enumerate(rows[: args.evaluate], 1):
            data = load_episode(row["path"])
            if not data:
                continue
            path = os.path.join(work, f"route_{row['episode']}_{row['seat']}.py")
            prov, size = emit_agent(data, row["seat"], path, version=f"route-{row['episode']}")
            wins, games, margin = evaluate(path, tiers, args.episodes, args.seed)
            results.append((wins, margin, row, path, size))
            print(
                f"  [{rank}/{args.evaluate}] {row['team'][:20]:<20} ep {row['episode']} "
                f"seat {row['seat']}  recorded ${row['cash']:>9,.0f}  "
                f"-> ladder {wins}/{games}  margin ${margin:>+10,.0f}  ({size:,} bytes)"
            )
        if results:
            results.sort(key=lambda r: (-r[0], -r[1]))
            best = results[0]
            print(
                f"\nBEST: {best[2]['team']} episode {best[2]['episode']} seat {best[2]['seat']} "
                f"-> {best[0]} ladder wins, margin ${best[1]:+,.0f}\n  {best[3]}"
            )
        return

    if not args.replay:
        raise SystemExit("need --replay, --list or --evaluate")
    data = load_episode(args.replay)
    if not data:
        raise SystemExit(f"not a kaggriculture replay: {args.replay}")
    seat = args.seat
    if seat is None:
        rewards = data.get("rewards") or [0, 0]
        seat = 0 if float(rewards[0] or 0) >= float(rewards[1] or 0) else 1
    prov, size = emit_agent(data, seat, args.out)
    print(f"wrote {args.out} ({size:,} bytes)")
    for key, value in prov.items():
        print(f"  {key}: {value}")


if __name__ == "__main__":
    main()
