"""Route-replay agent -- somewhere after episode 93034871 seat 0.

Generated by scripts/build_route_agent.py. Standard library only.

One recorded 719-step action route, replayed in both seats, plus three
runtime layers and nothing else -- no planner, no scheduler, no opponent model:

  * bounded WEED repair: a scripted PLANT/BUILD_* onto a tile that has become a
    WEED emits DIG instead, replays the intended action on the next step, then
    shifts the following steps of that unit's trace by one so the rest of the
    route stays aligned;
  * SELL-slot ordering: the SELL orders the route already contains are reordered
    among their own slots by price impact, so the largest price move happens while
    the market is still shallow and, against the 10-order-per-turn cap, the
    valuable sale is the one that survives. Nothing about production changes;
  * hands alignment: the hands list is padded or truncated to the live hand count,
    because a route recorded with N hands is otherwise invalid on a turn with M.

Route provenance:
  episode: 93034871
  seat: 0
  team: somewhere after
  recorded_cash: 154009.0
  steps: 719
  hash: 18057e31679b41ae25fcd7d5ebbe1477
  selected_by: panel win rate, held-out validated (logs/cvar_report.json)

Design credit for the three layers: Kaito Fukami,
https://www.kaggle.com/code/kaitofukami/25-27-strict-future-v27-midgame-meta-reset
"""

import base64
import json
import math
import zlib

AGENT_VERSION = "0.2.6"

# base85 of zlib of the JSON route. Chunked so `ruff format` is stable on the
# generated file -- one multi-kilobyte literal gets rewrapped on every run.
_ROUTE_B85_PARTS = [
    "c-rk<+io0La{L!Q_XGRJi{Cg>uO%#JC{WT8>j5zsz-t&V)(>O98T;?nl6|SF6B!wqd5Yo;_||H+s?H_rRAyvk<j?<i_8",
    "-6g_V>U2cJ?nnpZ)Ol<L&!jKHYr&^7Vdq_P99v&tL!h-~Z>^U%q|(`>((K*Wdp4+vlIpK74%otM=iCuYdjJ=BJN8-rSx",
    "o&feWUoGn((*PlP^cAo}+_`KV_|MvC6huzJWv&H4)>mPTwcR!simdBrey1#q>_1%}#|G0R3{KsNAu}>f0{rT&s)18)sx",
    "&3_hu>1VwX{<lp-GBM;^y&E3<imI&KJRXCPj_8S?|Qi0;8tKD!`q%dO}7FKU~)Ti_uveVBYE1B<!G+^Uy*x#y1jX~v(^",
    "*M=kOoE-6rEEcisP&;d(aXc>3<AlQE3uy5A||XYLB`Zl?D?na9nS-Tl;vrr(XN2b%73YDAy!zD|v(HO@c%^T`-}GnpOR",
    "%64(a3p`n+)BN7u>`n9Vqvt1cF!j)0o|db<>0uRyzjC(=Jb!3&z?0BeFuBWq?ZKK2mZRCR_BZ;D?bn?y-RQd0C-1a`?K",
    "Y`)2^JST4Cc|w&z8{?w3S7Nj=y<_k?LzHf8*~XSi=1Y1NO+<H+>P0_c(s|cJ_WoA7Tr4TKCF@_rIi@-uL=+!@Er2@P7w",
    ")>Uv%G!*{ss<gKzcyh-OU4ZJ}5Ty=W3Mjqc6AHmcgAwO;0h(05DcXxZcd-vs+Kke?ne7ybmZ{ste)8eIX5-^eUJ!aa2!",
    "&`eW9`hMG1|pLm8?W;1W55G^)%G9Q-{~AT`RLa5|B5~daPJ!Tao~gl!xj8FC0K>e1fJF2v_oz(pTlsr-W=Tp1c80PA!V",
    "To{N!Dbtp)nzUXVouqW`Gc35ZASAtwVUdr>9dS9ySFZ0_$riF9hAuL3-|mxIxAAb0@I{ppgeGw473EpS47OMiT!%ek&9",
    "!OdRSv3|Q+|EtOGec(fFRFFIG7}&l-dpM6_^yLH=|90x#-yx(%Iu6;ZRyrgz{=@OEg99u6?i9yfnOtZI5wc!-C(!q6$=",
    "RSU+RU<WKgNV2BSDil{(##=JrCkCB>XXI^e5EM#YPEw<t&B|8AcA?DU|ic0j}OI`*zvi;bnCI%XW2)WcnhJ@*k)0UC3!",
    "022hNYe0%REf@R^HhOZ=}#sHpDOF()aQ3eEwp;D3YldO6*kYz7;V{Ja%-2cUzSid)Z04)%+*l4Mab4f1Ia4jkngLZM+9",
    "ORKqPy$l;q8}&reAn2bBd6-PD8rTV;ShkYjLhz2qlZN~Wjy6YKV1>MYKHe4IOsYCGv#Q|_ZhfDCd1rbxTQ(GxeafZt%5",
    "{b&vV-U?&|4rZ=I<vCO$3`4%Fu__csqe?C$UX3Otz<!sJfKygQ^}uDZibrbBliem>3sJ-r~}6naqxe8ws6lznm9FhUk(",
    "n#-RWx*|hhDF!ET1f^sj#}CK%w|_YeR6D$W2Tv$wx^~QKmO_!~3M8$-ns?~y=V4~uKlJH&pqYGX`${A1Hi4KOxm*SloQ",
    "-?;mc{yBIkAffP_!*NG3&>~@hK$793O#rCFponB4-+yd&o=XwZfo@!AtPr?(X)f1_nBM`#<hC=-c`D{w(d-oq~5f+rZb",
    "-(YcVen(-kz5mcs2ZM_xTiQ-)e+wyTEL<9~dj<*8U2b3lCb`(-u#DWej8K%CkCCsVB1=C}f8WpNdb-J*a1l2a5(%|OKD",
    "u##+5n!a#+-q!z2vQsnq{dYQ<)<Jp`F6X}(KkIUGLHdUX7ov46maUaXz{d8CP(iAG0DWeoy&{52$se!J0#&YzUKwYQ^W",
    "3<$dA$jT{)LEAyLEt5mc%RN=uC~fY&d3o#|+W5>I;zWPIJe$&DX!NI@+ZWSb4kbNyQEn1>*}w`uvE&FfMi1qP5E(?|id",
    "5A6SqQ$EdD;>S!ADPMMqNh{t1dxB^+sa`zJ3Rc4w2>(OT0XC`R3n%&5qJsWgmc$V3d28*Zmv7eQm#3BmKlm%n{E6c%fC",
    "FIq8liP=r_8Qv&M)TjP>`EUu*oumlG}`FE4O5;fneO^Ij4*Ota;*Wi>$K&TZ84#9I{|Rbz*0H`C0w`;gZToGI%v54an8",
    "q-=Xlk50bk~#UPFMcHJS`SVz=whE&7WCxAZ-MIMP-4e)lYIc%K@`;M=yAsTGC{=lgt!5q~(65V{tLgoG|rX*#HIs%~qc",
    "wHVh_~7vV`0@77d&{%pr1qD7SziSt-#^mN_gjk4frP9N^EI3376YRT!wMX{tpt7GW=Bf|kG!B{6Dr0DrlEv7(~jCxN=^",
    "95O&>bL4N%g0^Bfw<RPT@wW_XnN3{$ZXDzuhsA24mhHl%kY+9EzYYrz@V>lQU?&vB#!)M~A@PH8gd+Hz#sONKuywukQX",
    "ZDTkyxTp4&`L|qfA_cyQ583K+FElb^vtFYkj{)7iSVXIjhgm#$VYPu(-{pbZLZKCRBS}!$+05D-w2;m;6puy9g<w$wp5",
    "ozSO?2&aVw1zXGO8+X3?lWt$0OC1&6W^MN3}x8y|IoD@;gm?YK~YO_!wR&PPn+SG^QSzyRj*AS;X2$zY5ZK?_q@yb}8k",
    "sHB=N>DX(Nfduzp~d{z4+y+~4L=I9E_&(yCCwj@w6C}BD@RHy<D#}Vf#Q^R-3coh_6hX%gk6fV*A-VZ7g70Z<&=+V~{K",
    "LUv$KrU;7U@#CAeLA8ct&5u>?KwA=()1*cNpv>yyeDw#G)Z!_wBX6KRj%1ptKqV?tWY_-b%hh$GJz4!DoSB>OepaZ5lI",
    "0RDI_p}6pBQ~OL3ADqG&G>S}2=2(}&_VzQCyRr_O6wMBswGhGD%e*4yJb4-6p(`03aebU1l6Ir4UFG)FGvr(>}$nuhN0",
    "D(P~0lq~5{lX|8=K(gKnc=#%BAqSMFV$B%qn}$jmjv62|(mWDR!J&(kwE!Sf!gjqEO0iG5qfQ(8GW?p3mO)Rsz2xER@G",
    "fHhv|4?|FU^h>JZ#G_U5NHN5ZF3(r;M<RG%ks`8PK@zN|C4*J&Mi)gx4At4TAA5&mR+vSO(&?KLRkq=_{B>$3wmHVQrf",
    "JghvuX7IumXgf-TMN<(XnnHh*H$ch)7;c((=ONn`cV}Y8d0}E}~Br$9wqyH_<q&4wTK_nRytso`5Ig$yE%tJ=8$&(?yX",
    "89^`Nx$+G$1+dr!1F?O0Blp68}^)PxGbP>Sf23qv7>$yEl`3Ot=TOR?O~f$&Z)QCx<v~vAA|^5w5y9WW{|Jnxi0|A78?",
    "FO8na#I?AuUkLOF;*LR-_T9_1gPCuzW5CgsUT*^q3Jz(`mwT`It_k?&hJ&@v_U=+=#&%}}osg8}48g?_;ys3Dqu7hv<N",
    "h*n3NPJ`^>?mJYKo;g(}z^2CN%S?N%(V42hCQYl))wnR?kGJrwt}oT?LMkL}v%zuJ3->K11jP&q0EBeM33$t@v6R`nx>",
    "EFHEy7M9q1O$<Ja;rNLTl8;ssCVJ=pwFAWXWs@CxI5Kyhe**J~4fUO+ZWTOt1{V0ZeF!JH!E_@a0AAY6xk9jI`Iz3!AK",
    "mL_wkoGcHRD%%S@d*x8+cB57h=gdZ8%*deA9rigy|Xb72ISusqrU(2Z2^!!q$tOki|G}=&U<AboJtRi)6Txm_i_t=_;-",
    "(f6Y<zAkSSDs)=NLoKp#AS}nB+1<@jA{yk1ommBwgEFT_Tqre37oM?Nam~+u`!q9m&5T~IS|eK7z`jJsJToN0?v7%dTm",
    "Iary^o6imbzVuvCQl$MHZNB;!Lx{;dHd89#Mh<EnHLvmhM{0hvustnqW1DN$l7=b(17loQ60=p)pc*ND>7wM=Z=-5MCi",
    "b8zFl8ueY#)ee-71RQDd%!^CIo{g5wP^__Gq^nBYD^y|zbpMEK?;zSCQ-S^BDi!ybRbpo<ai!v<n$BG`H7m$?NLqrGE&",
    "0R>B<W+#23W@h#(csA5@qm{W40$e!6Nf`5MgLsCW&gS(<l$?b-S?RIKAe)fLq4{eF4QttTfXU$%7G!!c*B4#O0!Lj5u^",
    "g1xHDOWjwlPq=)H5yKFehnOWotsX1j~1xs2G-@-3Q$oO5v_Af@TXkB;cHb^9X8<0qZ_^soSB@sk57OL{+YIOthyJYr6F",
    "69W^`($wMMpT*2D5644-GK&K@s65$%25-T&;wLka4m`8ySHx17!Oi3!8n9^^oQ`cw#dkx1SfJ@tkO(J27V_>@{$_0M?^",
    "-(FPnr2gQH;}DWynU(jfPknFmkW$K)B@v2Gp{UE1l%FQzKl)2{`v>`<Tx3ng^W@}+dJElF@V*>h$LX2FO6a|k}QRue~!",
    "fg5^utU)eS8xp8-cRa3M3Gq}r9vVZnA6hNL4g;lOG!addqyT%wfvZ5NL6UyY7FG-g^JN8W>y@4fzUg#XVzQ2s@#=QdW4",
    "P6VjF`}8%_4G?fa}*s3E*WI=*`~|62LGu5TtJ~jZ)815ZHNsKFn|wLg<HJmcHI-p;W|>jN$d}4`tB>60B4DxV~CO@_He",
    "YGgx6lxKD-xJE<IjWva~zLmLi+^A;{WeiK^ei^obaN-RnXJ++`RL!;IQ8Yqz6kW~E*I~ngphF8!o`Dr=ER~Je-a^RQU-",
    "!2n?XNV}0=1i^8v|95cDpY2+n(1{wLvol0nKD7zF3%H&p+KStaIA7Cx>Vy7mRnheQf<0!j>t3Cs9Z`bQAa1Iz^d6q0(=",
    "@R+w__kT=pzgyxbUZz-0vL;e@<EZA7@XK;laPz>9@!FIP?9kh6#7fv+fcd)Xx_d(qTwtmjst@O_3PZnEQEjDW3BSG=Xg",
    "K{NFYimYsqsms&f9ZfG@&0geWx7IT52KX$o5s13=+I*&RGPrj!0VLaYK(k-!GhJbiB7cNRmU;ql-YS%uIr%CKt%MnkLn",
    "tS<`V4@Kk6vWpf?nZ{hPqZ4_2D()CnwXCbs`nfIx*`itzVZ^tR!t1TWE*$UFSa&>xc+fI$2mspzdlNl7vAh0^*la7yh!",
    "yhvtQ0Os&z*01Ja&lw%bwAg0-W78yn(`s?D@sV7O1kTie#+RB$LCL!;(_uNQo67i#kOY#2WzeeV`T=gD1CW}8e=N$;HU",
    "0AO(%jn=#nk%9yZpFMO3~wY^#Z$=NZe{bQ<2TrXtHx>c$~+9)>0dY;6CkG}BF4_6Dnv3)>RtitsCyMXT#JCt?o8SC5oo",
    ")_EPVj}fG1}4S~K%G{(dP(&xOWKPrP4h-Yd4<g@pmDOnkSocTmB0p6q<Q8Dz5eU`c3!hJLd&!e|{*uMud7qnxD6vviRc",
    "e0S=t;TaTgiKXK4WYxOH#pXR5cRl)vvp5o?SPt1i-x4~{i6HZZ@9>jX^zkCKl5|$krAdt>bp@m>FfyPpAp*^U>I<+(n}",
    "_+O#5sa91NbjZ5_?-oa*eUn3402OIwc{E>*TI{0KrN#)I2=Ftqn{n9Uy>n&0=@>4T}1Y80qp!84G4SVZPit5<p6L087>",
    "bEUgbWBqkimbtFuxM7JQF^<`wh3MWE@L)MiDJ7z`xO@wCknrh7fL;Jh(6F?9l6BKB(={i9H6qROV_yy^^YAg$*dOroY(",
    "{qSLy(T%{_5QB3yc8P)=40ioTw7~mEg3e>2k=>}JzCXKE%b+2sv>TUF+q<#RqrxV)apoVd0I_Q;8<Y!DB@>`${s+}Xw>",
    "4_WRC&>#-k9rd$=Y1saAM8%D@eRsvm_*`E}1+=^)o0I|z?3+ecl@xEpTQwTM0@2qH-KontayVoBqv?618|nOTtcA#_%h",
    "`xP3yp~eD)V<Bn?@Ol*X)XC5OMu@>gh>BJ%f!{NhOJd*<n9+z2T90P!35e7oTnL2-Zhzt9NUgUq{4v9b<?(}NkjwPLLE",
    "8xugk(Hz@BLodudCMaQqtLOFB*^K!tB$eWYCB)!n(N1V;?jT#k?K0ZBYhxs!WI%5rk@U7!5`0C)B*UQ;5yhS3EFUel~u",
    "CNFr_d89@rEGbQ8wyy;Yvv)ULWjN$39AL8nj73;jBCJG$TfkY)VqqPg<_pILO3e*J9G(RURw^ZoZo>5qiT+Uyr_EFg)T",
    "A76aN6jM0&+rYst)tu>Llbs8o?fMbYYE?wcSqt?9wRqB(gf&yCaV~F77{a{wLVN;fJS9%C&EN~M>{ATS8Cz~mKi(ETO?",
    "P<!}>jF5o=tVR4d*mC;~{;@Uk3Lk~6HJz6uob@PTQ%3@Y;@K5$|qYE>MVfmTMF9yGC$F~W}@Hd%nV%<`w|ri|zj>m1Vl",
    "O;wbYW61L~&Y|`4P)E*q0|SWUpC;UIQevcUi0f!f4z`ES*4>S?!3>Wdo>c#zH6%<wH7x|S5hM$hDkK`JbKw<LD8rghO5",
    "BnPfHM8X9YM~v9rPrd>vf%WR&`P-?uqJ9u7NT3n^&ekrt)Fl9-6PDEa&v*d>w5y9PSh6oi-&#6Fv9Nc+UvWsnDU63Zx_",
    "-ieDN#Z4pA07^>%(QE;3c=uk;0$Y~HN<{uT|L9cMfgA-`d!9|X8Y@_94M(2>k#DT)8AWW3lHLa(2t1KmzH6d@Kb+|d-P",
    "|mzYx<&ZyX(V+RPDY3~kyxhaQ@q_l8-(L@Fco>$bRNe0aT%ezNMW2902ZVpLCNt&%B;{lEPjI6#c<x9B=MdZG*?x#rZL",
    "0Q*az|CVk{x-L};j-Iu`}z5e>*;gEJL|l%~>hEj-m=8$1y_1JJZd&Qb?Du`0xwjx5hg=?gAtiQ$KZ#x8)NBTYIY7Q&0G",
    "?f>T$MNf~SloN2-%>N>-K*X~OnsN-w{q!N66%>|Gi*pIad(ev89cosQk>%Jlt3+cA99EJhHS?1<Q}LNd&0=genkbo2g4",
    "JhUG1VKbLk@*)r@v25W3IBoXJ*w_U{-y98RU2`n$aw`rI9DKa5BwmTyL)fv#M3iaqIh3vecX%ZSz>vyv=*Nb;Es-n)AL",
    "wp&o|Rj04bOha$&4O{n^She30)06^eRwJiI?G;J+TzS=~g(td>15KR~ma;;zhj*XL$SVg0|wcxB*AiL!5GvjObQ|vk<F",
    "I^NlaE|~Bk)o#QE+AK*gy=U>j^d0ixv{7w!Nc5blYK4Ls~OK8ry<c<1!x?icCNuo^mu0w;|%u*p-2*a;6jL9L`*tHGFR",
    "!5h9ziip;`Qr!8SN<?&H|(U&vNW3mMNrD{rL6>|<{tH<%VNCq$;0*0$T4%{sFMppLD#qD7?BPkHlikB`ZtE+PJAWu$CC",
    "q&YC@gPagitJ0drD;FaQLG*tPdEY-0g7F>uHc@I2^h(r%wqDdAIzp}RwOrt()S$@{O89L-l2t_w%!m0oK;_QJmAp9aN2",
    "Qh*(&jj^RdB&cT2t#_+N|M|%?pa4EN(0jgz7J9tPT8Vv~hTk&SS!lJ<l>ab5?SOse~<T#RP$Pg_xS7-v~32s?(fCL7u@",
    "5UTfH^OA$dXQqLWKk2?KtC~8Ake97#s`?_GDm|Qf=LJqMhSko$|kemgN7H?Pu=+n9;ir7}VKr&c{NIv#HItYT@sXF_7<",
    "xCRpmCzf9p`XSp4TR`iBq>iIXqhtstJQao)3sdj!QHG$cnW4|R3&yg5n0H&Y?Vj;hDYVs57@silC~(*ASThnpbiE`fw%",
    "vm8P{C<_I!Oux<dd{y=vWtpZ4ukzQ6mTcYzJhthtc^sG;NYN;ohYg8g$KvljTRResjU_Z-|dY2*79TAaru`Pgac1n&$p",
    "wQ09q9%ys2;ECq7PH4#VsG~`hvR^bek~or|GDoy0RJCJ#?lbnsX%*IoCuP#e1#<TM)TkUID1rz|L<S>?ygZMj+bA5GWk",
    "Kn>LUbV*+_!uz@u`w~=rXNnwk`^3Zc5^4%$TBmgY_Ol3wNWy3x#=lo`P23m%P)hYjT&?K_4(hUohVns~4Kd<+f@Yus5*",
    "|k#g0g$}X+lQaB6?AXI9{au#%{4TGktz3u6~Nm(1?Ch~d$O?y1`+(gbdI$Y;D@zZDFQ0qFCsc=k%D{-lKc;X2<&(*Im8",
    "e(gMe4c`-_5qoco)#caCJXNqWvonL`8Jhs@X!iM{gJUh(s;32!V)9n0f?!!O@=;srINH+#8YUuyyg%t)r+H(W1s+QU_c",
    "C!^2|zS`dXM8Hmf+*)-R7qG?u$4R9Ptv;T-{Sf5*a-?CR-R08m(;K&rM+(JitZ2lzK%6{yd49l`Wz5UrJHx37``CM=Xl",
    "cAWYuQYJ|li3lAYDDN3KGu6M-5^h&a?o9<mXR5IrA=hi%r}2%U=r9zqdqY93Ku58@{6sG9EOniXDX(>a2L;g5#cJI~Ic",
    "@}=k#uJja(Mz+{(s^?E+qk$iwQXUQN=4GXsB2=r23W{6BN0QV2l7M^&mtEL6wVmWPD`xSd{Qf;MNpfOhDP{Tem%@B27)",
    "%QOPJVUfkE_rYE>bu1D1@fTg2+&tX@BOBXD79oSvPw#AMKLN_+XT}VBv>y)*!^h>1wMUWg|^9HRRi{v?72XIfV|DZ1-h",
    "W9$7-M=Y9pGuz&@9bgrp!1rxwbNCS5%ine`8(sfgPOA-@hX=oPw7FgyE#p_VWb_taAFnpc*Wajv7Wa%V%`IvE$>_FH-y",
    "-AA@u~nCyDzRh8a5%^XfWq=rD1zkSx`1LNV}>O@l93#!)}1q;6zHRE(jBt{g@JQqEej)>nvSp2W8fc*iE|d^D2=NK_F1",
    ";9e5ha%+uJ+M}y{?uwWf7dtTDz>rKK$)&_zsp}WPL#?ypVr~d@i$Kn;3At^|pU>RD6O>#Z^A!xQ75>V&D>l-b>Fq}A%r",
    "zCX1c4BD>4Ej!?GfzhvwMG6dqW8FIy+y&41-gQMM48>e^3f|pX@C_%GBf3q<zvp1L*@jD=w_%>l3pf3bZ1xcx{0ELJ5~",
    "bCOOB_;2kL2$6jfoNQ>wbRw{`T8tW`6Fy}gC62fo$_y^El6%d;a5Zz%oT!)h@tulRr+?11VwG3>PYGPrkn(!W!ZgYMeb",
    "|@9)_Wq;O(t6NlDFnRNgPW7_AVLxs5$E6Jx~LmLX=b!gmGUD6yl9<|OFZR0ZH%-UPU4p>A7gSmJiv7=!1a(4hQbOhjq@",
    "+2a_F<&Vl&v}*<O4js2-CK_Pg+e&e~Z<xLk~AuC|i^6fTp88d5h>bp8Auu#%97Q@5HcnOW4fO;QRtBJjLcqut%+3O@h$",
    "!sPmXr?S)`r~k0L8w107Yl#_3CA07)&=T`S=wuPHKv0%E+z!(^>T?}218VOQJFE}QYo_Ahkmph8d>KX9<j(Y>a?=n&h3",
    "TNn6xB;4j<EC(0^V1VB=t%!5D78A+@0caYL25AVkWF38+?%>(zuJzzT2rBOI$SPqR8s<o=h>|^6DD{Iys;!(57Hs1uT~",
    "C9|fg-X|-KaP*Y0M*6X3^Jeg)!hFlrgEyCH7T8)@G>)tOr%7-zU7L`u)jzy>PR^Ow`$R1q>7+RWHF`PiiFe@ciakaZA7",
    "hs)w_-HLVdh6jBy_0xt(2Ys!sX0=M4l=>o6PF5=&r|O|%t8`Gunv(qvt+w@bLKRic{61%RH&vjz*|`lV4LUm@Mb#%pVa",
    "10vlN)WmgcEl&S3*uTUWZxQ~Daf7@dyB4}sSenp5UUZ|JaCGSDJ!Nz6PSkaRY12B?xh5MtwaGG`LqX{TIngG=D#HNYm<",
    "xKp&fS2`BBaGT5gk!oW-qI&m+qjQMq_3t_=l*V3m6V7`DJxB@Qw$fjCm$S(1F=}rOnB-@F7dbt5b|?kvGjUWS4b{5B=7",
    "xcWELw9upTu@vvn-7{W|U|~dP?}pY}*Xjj{D9v=QWCRgxwOlsjWiwrH$>wHaV=ggcO@HGua55gi4(#FN}00?fr)IIm#Y",
    "~DQLYlr>SIHs6~$so=H$x5`hL=TGb`(x4TnR&K#wr+%i%gF#V&=0kX#)TSZc2Y9VO5lxSqEH>{7iidCathZ3K~-lE}(S",
    "eL2?C~38o)G3vsX1RZ9J2t-xU2I=knGTFxH-27&LgmhZ8){$dA0vyj!Z6%C0<LjDP#5S|T8pMt5K$p7%>iol9}@jdE_*",
    "D<12#QY2QfKON^5(+wvuZ$jMQak=F~QG#1}6bSZMQmQbDsAfv>fHD~;*kfF6XRIkiix+$|>~2v+aS8mdHaKSz7Z7TUCi",
    "rk?6$8giz@KCCW!BDPC+>4B^cBGy+yET;*sAbIAUmZvW2^RUy?Z@HkCcP3?`%(RZZY=ln7QEe28pUdCC`c}g;T+)09DV",
    "_9Unrc<Xfr`J7(o-rE%YFU_79l&m&>kWs6TuQoNhWRV_uAd_YC49=hQ*;yol-naVZRV@NpJ2D4yK&46eegZsYO*3^+n|",
    "vCadIh^9os#Q~jsyJ2L!-oxnfJ*gmP!r{<yXno4}cpp`f<kyLu<ltMo}`-9kygJDuZ<LP43tj{A-{(ghZ7>y^&{}I`jS",
    "NYi^m3P9-Vctb6u_X{x6Lx!^66tRr$(E(W+ARc%Yh}xeLM{8wl0#!3p)V0_#1ZlDK+M@D5g2zvblk-jJG%Hj1%e(Ztd)",
    "_#frvUpUL~Mjzr`D8LJq>_F`-42A<WPhd%q}J$4|09z}wXx8zqK{Ru^RJdk8zfjz%XG#`6>o{Bn$-4FI2)^^|b^a-t67",
    "?k!V%#2w*V!U(URWewDnQ^(mc#&c1m$a<*V(6xYvB{)*12YhVP)P7a$M1;$l+%=ErqL#E1iIikfxKrn?3VxN;dsvQ9KC",
    "3*%Ar*881zjGkfeMIv|5@<7bMiq>R|5LZ3gZUaLaNg96yLYnUd1GWnv}5fn8H}`Fp?3ZcKC9dV=j&l-UAhJHMwfm6|Bq",
    "9{2TBOR-V24utFaIN8mLK>;3)RCwWwk3c}LE&Zscbl@<7&8-edNZ?)DyN23CjXjmC|Lr>1mU|bu3r=^bLQg|4BZTX@vr",
    "Tdd2b|zruX_cij_Nr&7sHep!o*oTK_9gr%hHf}ziF(6v?@dlMCv8C)&6WGogs|LBq&jD4<D^liA8C-=g10PqX$=UmjlY",
    "t+FLXtagJyXFx!Z!dwVngnfY4pR0mW7nm|=W@g@z|Ddrw|0LAwP7s$PyB4a?J+N^7FxjD?@JD<VR8)fH)P?5qDf?PTJ+",
    "|3Y)!?=YY1(G2tttfFa4UCV<5EZD>Go@PLxd>})G{Y@VK@%aCP63JH",
]

_ROUTE = json.loads(zlib.decompress(base64.b85decode("".join(_ROUTE_B85_PARTS))))

_PRICE_FLOOR = 1.0
_MARKET_I0 = 10000
_MARKET_PARAMS = {
    "WHEAT": (25, 400, "sqrt", 0.80, "log", 0.20),
    "CARROT": (35, 450, "log", 0.20, "sqrt", 0.70),
    "TOMATO": (60, 200, "linear", 0.40, "sqrt", 0.60),
    "STRAWBERRY": (120, 100, "sqrt", 0.70, "linear", 1.60),
    "MELON": (250, 300, "log", 0.20, "sq", 3.60),
    "EGG": (50, 332, "linear", 0.40, "log", 0.20),
    "MILK": (160, 122, "sqrt", 0.60, "linear", 1.60),
    "WOOL": (200, 105, "log", 0.20, "sq", 3.20),
    "FERTILIZER": (100, 200, "linear", 0.40, "linear", 0.40),
}

# Per-seat repair state. The env builds a fresh process per episode, but a seat
# can still be re-entered, so this resets whenever `step` goes backwards.
_REPAIR: dict = {0: {}, 1: {}}
_REPAIR_SHIFT_STEPS = 8

NO_OP = {"farmer": ["PASS"], "hands": [], "market": []}


def _get(obj, key, default=None):
    if isinstance(obj, dict):
        return obj.get(key, default)
    getter = getattr(obj, "get", None)
    if callable(getter):
        return getter(key, default)
    return getattr(obj, key, default)


def _seat(obs):
    return 1 if int(_get(obs, "player", 0) or 0) == 1 else 0


def _farm(obs, seat):
    farms = list(_get(obs, "farms", []) or [])
    return farms[seat] if seat < len(farms) else {}


def _step_index(obs, config):
    """Turn index. `step` is in the shared observation and is not guaranteed for
    every seat, so fall back to the per-seat clock; the env indexes turns as
    day * turnsPerDay + hour."""
    step = _get(obs, "step")
    if step is not None:
        return int(step)
    per_day = 24
    if config is not None:
        try:
            per_day = int(_get(config, "turnsPerDay", 24) or 24)
        except (TypeError, ValueError):
            per_day = 24
    return int(_get(obs, "day", 0) or 0) * per_day + int(_get(obs, "hour", 0) or 0)


def _copy_action(action):
    action = action or {}
    return {
        "farmer": list(action.get("farmer") or ["PASS"]),
        "hands": [list(h or ["PASS"]) for h in (action.get("hands") or [])],
        "market": [list(o) for o in (action.get("market") or []) if o],
    }


def _align_hands(action, obs):
    expected = len(_get(_farm(obs, _seat(obs)), "hands", []) or [])
    hands = list(action.get("hands") or [])
    if len(hands) < expected:
        hands.extend([["PASS"]] * (expected - len(hands)))
    action["hands"] = [list(h or ["PASS"]) for h in hands[:expected]]
    return action


def _route_at(step):
    if not _ROUTE:
        return {}
    return _ROUTE[min(max(int(step), 0), len(_ROUTE) - 1)] or {}


def _unit_from_route(step, slot):
    trace = _route_at(step)
    if slot == 0:
        return list(trace.get("farmer") or ["PASS"])
    hands = trace.get("hands") or []
    index = slot - 1
    return list(hands[index]) if index < len(hands) else ["PASS"]


def _tile_at(farm, position):
    try:
        return (_get(farm, "tiles", []) or [])[int(position[1])][int(position[0])]
    except (IndexError, TypeError, ValueError):
        return "LOCKED"


def _repair_weeds(obs, action, step):
    """DIG a weed that has appeared under a scripted build/plant, then resume.

    Weeds are the only per-episode randomness that can invalidate a route: a tile
    the route expects to be empty becomes a WEED and every PLANT on it silently
    no-ops for the rest of the game. Repair costs one turn and then replays the
    unit's own trace one step behind for a bounded window.
    """
    seat = _seat(obs)
    state = _REPAIR[seat]
    if step == 0 or step < state.get("last_step", -1):
        state = {"last_step": step, "active": {}}
        _REPAIR[seat] = state
    state["last_step"] = step

    farm = _farm(obs, seat)
    positions = [_get(farm, "farmer"), *list(_get(farm, "hands", []) or [])]
    units = [action.get("farmer") or ["PASS"], *list(action.get("hands") or [])]
    active = state["active"]

    for slot, entry in list(active.items()):
        if slot >= len(units):
            active.pop(slot, None)
            continue
        age = step - entry["start"]
        if age == 1:
            units[slot] = list(entry["intended"])
        elif 2 <= age <= 1 + _REPAIR_SHIFT_STEPS:
            units[slot] = _unit_from_route(step - 1, slot)
        else:
            active.pop(slot, None)

    for slot, (position, intended) in enumerate(zip(positions, units, strict=False)):
        if slot in active or not isinstance(intended, list) or not intended:
            continue
        if intended[0] not in ("PLANT", "BUILD_PASTURE", "BUILD_COOP"):
            continue
        tile = _tile_at(farm, position)
        if not (isinstance(tile, dict) and tile.get("kind") == "WEED"):
            continue
        active[slot] = {"start": step, "intended": list(intended)}
        units[slot] = ["DIG"]

    action["farmer"] = units[0] if units else ["PASS"]
    action["hands"] = units[1:]
    return action


def _shape(name, value):
    value = max(0.0, float(value))
    if name == "sq":
        return value * value
    if name == "sqrt":
        return math.sqrt(value)
    if name == "log":
        return math.log1p(value)
    if name == "log10":
        return math.log10(1.0 + value)
    return value


def _price_at(item, inventory):
    params = _MARKET_PARAMS.get(item)
    if params is None:
        return _PRICE_FLOOR
    base, scale, below_func, below_target, above_func, above_target = params
    if inventory < _MARKET_I0:
        amp = below_target * base / _shape(below_func, scale)
        price = base + amp * _shape(below_func, _MARKET_I0 - inventory)
    else:
        amp = above_target * base / _shape(above_func, scale)
        price = base - amp * _shape(above_func, inventory - _MARKET_I0)
    return max(_PRICE_FLOOR, round(price))


def _is_sell(order):
    return (
        isinstance(order, list)
        and len(order) >= 3
        and order[0] == "SELL"
        and order[1] in _MARKET_PARAMS
    )


def _impact(obs, order):
    """How much this order moves its own price, times its size."""
    try:
        quantity = max(0, int(order[2]))
    except (TypeError, ValueError):
        return 0.0
    item = str(order[1])
    market = _get(obs, "market", {}) or {}
    inventory = int(_get(_get(market, "inventory", {}) or {}, item, _MARKET_I0) or _MARKET_I0)
    now = _price_at(item, inventory)
    after = _price_at(item, inventory + quantity)
    return float(quantity) * max(0.0, now - after)


def _rank_sells(obs, action):
    """Reorder SELL orders among the slots they already occupy. Sizes, items and
    every non-SELL order stay exactly where the route put them."""
    market = list(action.get("market") or [])
    sells = [(i, o) for i, o in enumerate(market) if _is_sell(o)]
    if len(sells) < 2:
        return action
    ranked = sorted(sells, key=lambda pair: (-_impact(obs, pair[1]), pair[0]))
    order_iter = iter(o for _, o in ranked)
    action["market"] = [next(order_iter) if _is_sell(o) else o for o in market]
    return action


def agent(obs, config=None):
    try:
        step = _step_index(obs, config)
        action = _copy_action(_route_at(step))
        action = _repair_weeds(obs, action, step)
        action = _rank_sells(obs, action)
        return _align_hands(action, obs)
    except Exception:
        try:
            hands = len(_get(_farm(obs, _seat(obs)), "hands", []) or [])
        except Exception:
            hands = 0
        return {"farmer": ["PASS"], "hands": [["PASS"]] * hands, "market": []}
