"""Route-replay agent -- Ueddy episode 93065370 seat 1.

Generated by scripts/build_route_agent.py. Standard library only.

One recorded 719-step action route, replayed in both seats, plus three
runtime layers and nothing else -- no planner, no scheduler, no opponent model:

  * bounded WEED repair: a scripted PLANT/BUILD_* onto a tile that has become a
    WEED emits DIG instead, replays the intended action on the next step, then
    shifts the following steps of that unit's trace by one so the rest of the
    route stays aligned;
  * SELL-slot ordering: the SELL orders the route already contains are reordered
    among their own slots by price impact, so the largest price move happens while
    the market is still shallow and, against the 10-order-per-turn cap, the
    valuable sale is the one that survives. Nothing about production changes;
  * hands alignment: the hands list is padded or truncated to the live hand count,
    because a route recorded with N hands is otherwise invalid on a turn with M.

Route provenance:
  episode: 93065370
  seat: 1
  team: Ueddy
  recorded_cash: 89408.0
  steps: 719
  hash: 044a7741e9adc871e459612674e3234e
  selected_by: panel win rate, held-out validated (logs/cvar_report.json)

Design credit for the three layers: Kaito Fukami,
https://www.kaggle.com/code/kaitofukami/25-27-strict-future-v27-midgame-meta-reset
"""

import base64
import json
import math
import zlib

AGENT_VERSION = "0.2.8"

# base85 of zlib of the JSON route. Chunked so `ruff format` is stable on the
# generated file -- one multi-kilobyte literal gets rewrapped on every run.
_ROUTE_B85_PARTS = [
    "c-rk<%Whm*a{L#rxllbxddHS(EMeG9fug1`ZWI~~cnkx^c+vLG@V}cQ*5lUA%*cp5=TelxU8z{Q_q<PLWMt&8|8wzgzy",
    "I;~zx{FXPrqLL^!3x-hu=QmetG=*u({Y>Ui|y-|M{=~_4JpgkAMIDkN^1Fe?NWx_2T2FZ-3=J{Pgv&zuo@w>F3+Ki_44",
    "m_uGrhx%v9b$Ia&R;16Fmn-5Q4Z$EBsA1^MiMqmHDxx4@6;&OKU`R9lG4`1Iup8m&rxBK7AVaGmydjIFIpHFX^4f^)$#",
    "dh=M@mpJexqo>4`0dm2tI>z^f%vkyyF0ygF@Edeaf4Sm4H>@n^l3a5UIRw23un*m;jty(=45u(*Zr@+yFTCDzTZUS>Gk",
    "LEADp+1+6~^i|1ZPwH0}8I-7lxbaMsuTOa(tnM|g8Pe*bBC+&*p|#*1kD-TCTqm+pMLh`!u^9WNrgIREsIopJWfsCQ^8",
    "?ckgb@Mx4y{d<4AUz&#>J@3px*QL2U4VQiCVHAeHN~g=&f8OLcJHf1A@Rt49J7YE&4l`r+H~ft4#~lvc*>lG`?=*yVnu",
    "2vXBMvubGlWMgK3mSZz>TbT=;V`kXemFI^f&oDIzzZWVVpV2=8Yf3<2#NYp3dGc-Un^qPUGJ4;QcS*r1yP3obWCkIQ-w",
    "io4P(X{qP+gJGxaCfi;;Nrosi%=c(hfRoT8T-h#0`0)A@Dh(0ZNe}8wkdH?v^pEeJVpYA^W%lVnmY4FM~5tc~#9TUyL;",
    "np6sC)`6vM`ZNl;3{A31Pkz0uYX~F$9-JZz1!6OYqUum^Uj!$10&p7xD`LcF-F`y;rD94v?Vhc_hH!EtdHpcI*z?ykRn",
    "&b{ggcrjfM9qeIW7(Nc*wDAB~$_bfDrvrEFhj13}+BpMT)#w7I?v@RUBz^_B(a!7=VnkF>^MzWFV10&L5?ebVDnQx)K5",
    "FKk%9J+1%K=zHI>p_VMjT{jG3TfrXA=P>$g1dBhNdJp#=QbQew=&Gd-$%_4OeCy!A((g{P?Jb>?hR{RSo9+a7zcv{g@S",
    "?2@3$|lIC{l5nvi1vR6SO>l$xyJz;G#dFeknEz(5qxHa>!6Qc*juI{~zG$?Xho<{Q)1#16VywojCIDhVWC!X(a<FK}g=",
    "d+jy|Zo#XJ8qSq+kDQyAB%p$6QAQ~#Av>!y(TOC<+!3SgW@%G^_QOEk-_ySr$MzOu2I`*YFM8mOYp%~b~u`$RanV<<s!",
    "GnJ6*z;SpLHCTR<Dd*jDu+WHeC2G}o!01KP)-p~deBc#^sbuW`vwL&kHL&N8t^`I-cX4!+Xq{k)SKDx_SjaCXq8z```=",
    "xE+wRtwTKUAsnPOV)jhHWw54YQ&HV+Sfbu5_@!jyI>e7j4-oOg$tPy>TT%ytu?Q7;HWNq47UMvkGV>RlQm3svB0DidpH",
    "oeZ%i4PnBdO4Ir{emGv~`Qtd8?QkOxHmy&7?HKB8@=nGhP+SF3zooCAn_0C8y-&{#t%O+ZEe8m11Xo*mTm>eajE?sf*!",
    "o^!vbBO8ts3o`#jbFC67jOcMgWG2cf2yrH1yRoFs5>?Ahcp|32yK2@4ltQxTe+qkNXLFIv+n=lx@9}KkxTe_?kL8Idc$",
    "EBsy_c#zP(53bes{J}dHCK28J)%DJ)RD}w#wWGeMG6iQQs{17fa#@^Qy4An#r<9(Mlc9e~Nrbrou-kMKkymJ%fM`%rSV",
    "AF9pR%@b%G7dOX=ZOW)yFlo?oo?^w8=n@HZGeW^`@|25bLv<Cd7L^^V|+P2$;iB&%8FWx*|M`z#O^#cw#+RrH)B;c$4J",
    "T)=jhVmtr4$614O*+T_@W#XoGY8qU(%DD;R$|8=&B8dy@x0#E?R8UM!T!b~ASK^lZ&Spzdv$krz|F7)SvDWXH&ofc81_",
    "f16}fBjWfm_yjVVll;;a>jCW`m|)81lcO9~c?G)vq0s;i+2xl>Jkp|q`7H~42(;hqdg*1G*^u*iWw{^nkw*5!u@{a35Z",
    "W5jINL6x=Z5{$OdbewgASU&vy+8eS=!7i(P(%uZt<LBTHuU%;cQdJIe@L5;jbLB&Vce<Pks1NO8?=JOiL<wHRKV{3E$r",
    "#7rYOWJCl8ob{61`?`=o|IYUCBwF%sxNuEa`eZ#q3+YGi&xqinhYlsF%roUs<0cQ@%A8|q<n3#&~SD&R+&GQgk1LwLtP",
    "Vm9t{rS_~pZ6;-@{{Z@^Gv@MkbJ+TpWinlp#ut8AI58z>J&SRPKFgQc-!LiIWIe|L}$wr;x<x#ju?g_QctIpqjHYylbJ",
    "p=h7C|+t$7TMR1$iC3o|@Qa?&Z88zqh9A_q*Z+vZ7Nk!#UEJlmWzXRa-3WY2L=8pz78S);TVbG5Wtbjjeo5?kmw1y{qF",
    "op*9yg@3C#CzRt`_)twa&s?L>H|y0punpksX&x=#9<<_}3(GoIeTT=L76`4R6A7Hc&dbccz(P7>S6uUy8=OTBc+%a+HX",
    "XLpi46|(mR7a$#$2SncYCN*v-W^sz|VGKgk?vU@WPkTi2{DdDO642o;zko=A8q2t`^zko%PgRMOF-%A(`h&<`%!3N90?",
    "Xv?nX24z?s=B0t`);!_CA{)kVd<jFd`&hj%GZ0WBgC#{fzd7$^uia{J(TxU@Yub1;tV89;e3(HYmp#HsYl;SAU$s*p?=",
    "X61Y*pS0FGk&qt5YHh^q(!XNTjB8~FQy{*AhZe8IO<d==hQKAb8l#!of&Ikqo=ld(A==P`r6hyF3`;gk~qpcbrWW!Sd1",
    "d2;v}g6U%_Qn6oO!k-CU4PdkJrYnaqhkG*06Sw5opUyoNz^Ot9C`thd2>+n&=P6SU7?_I;f?D6b}LZrcXK=0wO^^L4#$",
    "@b)efL8n`Z;vkg(($%g_=(w1h<(U2~$DszQmz+?IAr5`03ZKm(Kf;(34%c}PY1R#JSrxHOe#s;TC5cTg?srpil@SCEJA",
    "t68+7x4VclZ`E1lyXxg&&QMA-~ztdQGQxCOE=L>MG*=ddivVDqIt(jlc``c4)G%{IPcP4!xm$w=0lp5$I=s<iHN6uiRL",
    "?-_$D`xmf0R7YwSphZh1THjK7}-~4Oa{8fl!&WJUS)={bk>(2{<_vl`&cNJCuK+K$ks{;jYShP`IU1$Hh+Bv&l&Jr|1G",
    "hs$6;PHXTblwfG&%@Lbe>JXzeMVjHcx12=A?S8xMi;_P1GC~xosC~-R=ztdPI5Ed;nl9A#uQAVazW#;$fGxhHu7B)osY",
    "GZF0sUsM;e30Xs9+joPteyokVNF<QRBuj#IJoHB{<Q4fCMj-}0!d90_kH4H(uSh59IMQcasa)59yLGhndh`=&NnHYe{@",
    "r+$0rVs@fbIDuQD%&`P<sC)nd*11;nL~MM|WjJ@Ap;mdEQ}%>gi`o0KQWfm%Oy#f1aMjoHa1awI8+ep^SSr#%CA-@2v`",
    ")jpw#A4<Sz#qO4&t!`*|2g<YIIk(BxXf}upx-@?F%A2cQ`A8t1pJr6P$i|4@t!=o0bhANx)>9*SKPkO$_&Nh?vm@6=ni",
    "zfW(lnK`bnaTmm)D*q}OyScJA;{*ujbEtffi7FVQKmQa!buAO#(kzENMf{%=<@1SX!F~Vdy8UlLPtZK%s-)K>x?&axLR",
    "h^V{(Qr+L^%~@rGFNi#uo@hP`JpkF?=Tb)OCJy0OLwqI?3zDO$YIucqQ`y^$F!lbV{Am2zKMz;Ovo(MahwxoGiB~d47n",
    "V?9IlP)1fiK8f^m2dY^*dyfNMr5pQ}>m&5+Owqdf6WOkIKIvF@ik!G1}Hz%GCy1F2nlxmDc>tsou>aYCY)&!h7bDBWbJ",
    "IKkH6q@&M@^C1-!4xIFIZWWsLG$#k~C{j1Cjf&4me+#KBf*lR^JUKLIZ&+qTW6lradbPN{L}sWUO$d~Q2hI-Yid*HbMH",
    "IlNsKkLvKXY=F-N&WVdOousZ=NgsCob-ared@@DAi_eZJ=Tih;il9PngD!j^CcB1#;MRCnAvN<XBt_rEV(r_W5-YyLY^",
    "Pb_1NP`~L*Ep}V6{4yBG!Fyd5X12>ZBzcXA=Nz!+ny~L;@u~YZ%5f@_I(JmA2h0-F<1yyRZVFa6GES}u5F;8O=C|mpxF",
    "u;pZF|3vES{PKCL5y7#&;V<rROtq)JVdLQJDY#unP@c6q86NVJb@w(kUC$L$!G+SkT3=G$Mlk+d~lM}#^8O~SUxU2Bqj",
    "NXv_+Q9v8DVGL_*~KM-S1n*->dHFcUPQr8-)~jd~K0B}NsfS7cM*qF`ht5>*CD`-LK-isWUqJaE)s6P(aTm8nh-F9b5y",
    "DIW?8<xqea4P=DC1go-JPKk;n;ditc!o-xcsdL8q=CbzSV!#W%+E$T_Wt|7sL)SfU22!%^f!>z=U<DgHG!#1AKpB$KJM",
    "7^x&V^isB7YwZEa^Db^Agb1Gle1Yr2|6H3l<{PiWO7KnO{jg)<|oPho*1ZwniH01nreAUM{o4vjsY02R_8@=<plxqp8%",
    "Y;{j%tzZ*4a@U^#M<iEYX1RLVLu1sWA3Zp_6=;iD~qI%;Xf*ja)J0S%^t{TF?R{dgGUI7XKRveh^7Jxl|BaQNU*OK+3d",
    "2`ZUc2Yn%4!=-M0?Y<g;viTi=QB}ZFxVkK4afP@iJXxdb`}@=t2pWv$_pi`(^hqxO)es}IV)3*lt<i!lyDp>`G~M~U?y",
    "<`0Y?%DnKy74xMUcpE>w+|qo5wI4Aeq&CQ@~_(B?wRj{}LG<&kI0hAG^}%#4BC6mx#+2;7wux)i`8OcE5*HRN;$imTy3",
    "XvpPzxdi_oB}jbL#jAVK7_nBWtRWYFf@pEEP@zT&XJ|9o(E3g{v?3ar;!f<ZPRUPn%y5D|+|dQ%xLrQyRTZCQKm<3Q*A",
    "GBSEQ5D9#+c~EE)+VT>UFnJTs@No>bzzudD$p56~)SxBCJ3gbYUQIx0Mp&1eN$qh!jPWD?{>nV$l5O#Ho^CRyD-SNb-?",
    "^U26QgM0+WHM{S@JW_mjr8>|jRy)y~)LN<5T)j`QDNKO)d6g%)&jpS^cy@s?X;~+EVO*J|%oX-pi2FO!v)-o2`4oyo4q",
    "Lj(pH)Wo@))Nrf^axkOj(_;{&ywo!ym#Aup89i1<ADU+I=Z}~C6;$(HLxhntB6^1y&FpC@#OK_sWg8&e&es#v|QF&OI9",
    "-5Y}}Eg4&<<v4pZLadTcT_gc7S-v3t&fN!?TW-LcSAgr@*~&OpJL!QJM;zVOs>XRkHZk5dP1e<$GqU;*~fIPVw!&ys{U",
    "vYugUT0mMeT@>DJ%m63?7c^oZ!Z!0=lVSvP4<{)kVvW|U!m31-E(-Ucs8i;kcdAX2tuV)Irn2CR>GvEZ92djf^r+pAd`",
    "%zeO1KpKl)!$Dgr(QHQvj~<<3rkV>ruKHr<qa|NT7nu-U5>O7G5u)Py*W87z${L%X^TgfDyx3b2gPAK&i!B&@Kcjn}EB",
    "{Q^ztJHg+;lh6o$Z2iSIiTa}#%=Uj`(BYA<R{w?<O1*xb8T0HG+Jmh3jC<2P`J9t|kiiswGiG?phdPO&s2^G9Va13To$",
    "ZqYNgeI%S3L;v%SKZ}1vK$;<xXx;@ERIPu@pPgCEbQG*ba2vLD-{L^S-)0)*Y*7K$l-<$JvM4l(LQnZcc#23S!=O_KW&",
    "T<Opjm|oh9Vz#DbhjtH(jON@Akw`nJA4HJOq<Y4J*`REY(}G6kx{yKLYOF;Z_HonFA<plg$@NnY70cZr~ouM`5pPz3mE",
    "vA!UWTj13L1)yY&0;zUgK?A@;IKskO>j@_)tw*OwhdOQvi1}lbCktnB?3n$tSNu+*7NE#OA?jF4g+_0ja*3qh0XQF|Yy",
    "wWLLHm(DD3*l3N5Ww+0n7P4V%-!P?t(xZ5reCz&Fu{(b%H34niqXOwluob-5(=7nr^>a61BQHU<pQm#+-LMGZUKT%jxf",
    "xHR+g$ds@;bBjTVX8}dk?cbawBJdG`1+<?=-pcyi)*iumyh%8(NwLap+2`L>3ac`)yPR35q*hEqM$ErjGl~;|CLh@uS1",
    "*L%{d*k)Uo!(`qJf!(D*k?|$=J{JOi!?zgsbw)halIZb(l|uVjHRxil7Rd*6c43qUUV#<NsLpC%Rr?*v9uU2#e_i6CaI",
    "W!AQ`^wCSAUS)6F{`YfX9T6!1dN4#hG(dV{=I>x398(NbwI6nX&joRBC3^Z?mPk%jV`u>*Xbw(1Ws%|tTSOD%^973AQ&",
    "<4%gOa{;k%;!QXuiB&w6rR?WI5)*D1CuhMjTJ(m4HNs{DIz8ZWipz}#YvepA;cqrt_PT4%!%88rXr*23-&nz3+TVOv##",
    "FeXDs0OUA7TK<{9_6C>lBF!1e!z~Lj}#@^Xl%G@&pzhK0IL|22>fcylburwMQlc3wrEWg@)A#aa&(i3WaK_NV;+Z0Jv3",
    "WDb5I*Ta~+A73^fvnAF}a46M5B*sn@iQszVd(xnR_C+YhEL#M0rbyPD+7+jc8YtpMmM<Pc}!?7v`B07VBTG(Dp5>}D!g",
    "&*yka|+*!bmD8oFSnf?*j`1DNUQD2C^lv(Ng1F3;}I!#RHI1Eb`^n0;1vrgVIok(#HeE~#Q1)@-jyn}TTw15xy!Rwta*",
    "+pmO@Nepo^s?geV;yOq0+nddxt`uM=eq7pk!Sy&u(vV%(A#;jx<nYlrd>N#C+T%yUh2gIa@LKO&k1S*fy8O{VYKYbcEZ",
    "gK2F`@0=VPOd5G6B4(6tvT*1i+m}_-j5!bixik|VJ`&O>iD1nZwK>aV3<DH4CX-Xe3dt0mq&u|aE+k{5tS$t4HWd4rS;",
    "K?sw4(QdGu`9=mu0Ar&#g{;t#w&43Wq{C@gEeh>chxuki>F&#bJ+IPH7+^s&(b3T`6gSh);y_1F5=?^kiN!Rc)_?lv1s",
    "KoUR;^4yW~0ICzWjo!hazlvc4DQ)PWVGsorxbL{&kefFzQG?h|OrCd>J8g}4`Sxuufvy!ELO<DZ74wFq==eb+q<SkXl`",
    "GsYa7EM${SLu7`>oyjxO6=8w=905JIIGLSBJ!>_i!vcq;wX!Ot(4JHdj@4)jd&b%lBNJDZxRXg`K}`Pgg6_~U~{F8bA}",
    "qs;RUPFPB2-6iaz92Y#}`pA~X!H)pP){#Hb7D1EDWWRHMt$a_9{*zeBb;nerEGM$E2)y%N|dq#SZUx6J5tF1{+)fq_^P",
    "+;9>AsOW=h+<BJu8LR}Zm^kuhD(DBs>~jnq{mWY`;R-qL1D7ER7jurzk(6hcAzsh~L-Ofqp}y$MCZIet-i&k<&#J{G<1",
    "?Bm_R9!=9A)C727!{&pn7&e^RAV@bv|+$Bg%~rV5#lEL6KpPH;ki8wJu13a_tm0rLPy$3AT{S2F{P#<Thrq@Mys+|Na0",
    "0u0|2l?evtU=6c$ovU-6#;@2f(Q!ZgmByC&@iN+D?jjDRZ^d|*~NxcgZ%wM;0Nc^o~J@X#*=7=9>wx-&1lw0RBBQ3Ip^",
    "p|id92?hPmIyQn+X5wJWZHX?omXO-tV{b2-=j&9BZ%VwvSKmfn_d?PCZn^1krP5zeq%`rtJ>DWRmmKhI4?9qmK|>(CM+",
    "akP&|(brVv*$ukNqfl62>aD2asd(BMjQoOVHZN+KOtwvDiA`I*BMuT&UvGijI}!do1@37t+rvU94nim`yeqRP`D;@>wC",
    "y*i2%A@BpiQ_k&wsKGYXygffZ(I_F{)hsR9aN3?u<%j!6zSOVWGxMSVV)KsAYvRB#xdB6^ZA_r8aJq)SJ+nQ-f#K;;Sk",
    "Dlhiiwks(9)Qa+h_ir9g0)2yr#jU3x-Xa?VKs9yPc&+3X90$zs`Tq@@~^|r9vt>LC~I_9#vxnDF`3QU2wz1vv*2B4Z@p",
    "MCKNA-1P1~|fM&ZUPE~OZQ??b1$I%dF6jhWsR%kJ)#h!`jpmR=~3k6wjne><NOI)5f?c-H+&<jg3FHVpb1|X{Yp>C{N6",
    "1vosNXS>GQo*{+h&=%X#EC64kDMrRj^gcP6a1;whUkbmr+|}g?}PJ#^#+@p?2|kkCc92IrN~3FRIr2?i*FY|(04UI01*",
    "xC8pQo1mTDi+h^Zgq#J%Xc1whiPlH<NIPQ-O-BV~95r2Ek59;l5u>cuQ7jy}7}i>a6LKOJ1jE?@*XWjU3wAjfm3Z(vH~",
    "xfot!cM)cQibH_)3khiaRZz_2_1B)x!Ob&k3Izh!4e3~*E~A$fNl3ACnV!^$N#bB4?t<z)!m<Sr`~t&qK!NM&gM4on3b",
    "YS>Z!Wvr-arFrn8>B<*!8)RPYI}s9!NY;8VulOr~tU3fZ^-lP`-Y_q{}m)dSR@9^&26PASC*>4#d2K;%<~8+p3kOh{dd",
    "_QlXmATnAK<z&cZiH!VVxI_?z-dz4F8=YiG#r|<u%NFoiCFj{X}jItF(CG&~e1&nSKXwm^#Gvtv1Ug_+fx{i!0Ojv-sA",
    "t+fuz*D8L5Fb;PG&(8~GbZx{ZHRgVw^Vp(vl4wI-Ij^cKSpZ-oXuB(*JgJ-EH{<aPS%VdYTqGJLmyEqYW<=(j#2@nflc",
    "6)r<0@%XA1#9<*GgAie&y=SE?5*8!=R-Qb~3iq4mJyGpn}qmQp*+>jvgClNyMe`4I6cM_RF!jk@I%a!%bfRJFqwiC4oe",
    "RBd`!HOAf+_ZHU=&P!r!y0C);IEo^L%D`hM#$LOqoOhTc;Y<{>55XCC%a-Ao*`n>FqUx~$Ju-wVrpg%wkh!{wxyni?gh",
    "k#u&K+9}40B7`!K_3;1Y1d9%A+wV+I*K)%?Yr)ur5M)1G}sYN?9fEFO$PCp@LmR)m#TnoQaTXDXul{%*w-2S0Q@041eB",
    "M6!kI&0&TsN)C6=gzK?MdgdY=sMO2#@d9KvZgK6%Za2w5cWU|NYxt<BxXMbl4YY_52n_N@P$G{NB1$ygwqnOx1v0wv8i",
    "r0x#d$vF&a^UD`VPUUaK^Zks09PHElO!2t06n|nG7X{Z8gT@d{IvU@san~%Tq)VaU|1=!=voC*z)QC0fPgNuaND?n-W!",
    "I^O{l}vD8sFkhPd)Yiojhe71s@o1D*v_%`Z>?mO@`?ZAI8EuEuYbvVdz?q%oijfCOF_a4kY^4LcE#=mzs+A&rv|ep}SN",
    "o=gIeYa>j~!#8x))<oq8yU*zgNKK`}LP7bR!TG1jE#~Yxtq03Gy9`eRl!3}a2`Tu&v>9;35bvF>aN$tHLdGkagY~W;B$",
    "(IIrF2S?blDmWqQjE1cs))Lv9oBNkTZ%CAqc}Lo;n-WOC=am6!r`6c@w`?5S0SY$omi~h`tCNO(7eI0_bv)(CFx{)d>}",
    "J<tcVqADY-iIm!NE8p$M;*kpVvG|elcF)Q~7TLMU<6ymoOGLn9Rf=C{GKQA-Kl6ubyqb!{-?2p#Ck0heDc7(5}vZ?rHU",
    "6d$0=|EY#04l=hx;^VgMp?FpN#`p|$rO@I-}R=hoVti65JJ_tyjwx71z3OGbGTtYk#1O1N(nJtfFDMcL<!~JvtJf8%*+",
    "i_Jb4j?4C*~*hi#Hx%ulLD*PRRWF>WCun1Kj?Z=0%6pDvZ+`~nePEF6_#<eemUR~o^-tOAz^L?(a-D)FqQV@Eqz&Y(vj",
    "Q3{Vg_2vK&pcNh$#_oGAcbR0`=p~Xu15B7!Ls->`DY%#rfIYeX!{CQcx|5FUXsLHw16*NSIL%|uodanmHJ!;M&}gqW=o",
    "8rP8*Z;Jj2N-dD4JmhT(mslctbFi!ExV!GdX4Ex{Q%pv4`POTR8}6L=$XhaNYbcslU+%?4~U^VJX%rBnJD}V<j?wZ@S3",
    "|zJltk<mN2kUcAU4;v=`Ap@^yFSg5N$`hsbPy<lt3`AKiBh2T{pSk|raC{&^0Y7{cJa8q`=7ZviePnD_}jGkZt_4jM-n",
    "X}sSeTb<cl$e%YoKnfAHT%J>1cVZ2Kx(Zt-b}(P&hSh{`+;emi!6w$esKz_52hlKaG8Lio)b8j!4Nfs5@KBXD6BEOVN~",
    "7{5vbZQLhdpAV@x-S+fJnG3NxSNal%wUhB&8{$<0w)GAlMK&5|>eEdtNTld-~ylscU(<C*xp^-`|3ZF!bGS;>{`j@_Bd",
    "JZ1t>_2j&jDmG8a%yK6Q;B6Qq<SQ01)l?;PX^sY>kiZNBl3a=kMcAX$0UNUZOc~mN`wleYY<XNOJ{KcVX^$Acv58aX&`",
    "!>hDouFiN6~=G2J_^WkKv$UjhNR}&=&f8ZiBW&ULRYwmM$Mukw$ATRx9O5q@UGv$%eYMQrAnRTp=)(-r;0j+7x~vOU$R",
    "tN0hRmRjME}e?&BFA)E?HmDm(B+HUw5pOm=){Ayg@6^UHKod0~3xw;Z|0Vnlbx#ls(bT0tTy$~qj3`s6VO2R-u3x!$=i",
    "H#Mxth4~hGd5X@BV+eui=6hPE?rC9IAr-G`KXj)-MJ|qS2!$*Otu!4ma3^zu0I4W^D=Fvf*rCynB@E*72<+-KMT1VN`5",
    ";j?t_%ClFDt;3QJNbx%J>}i0y`8TUGW1P&R<ehGB6v(K1C=LxOZs`I|{T`L{FSpc<3nc~n;D>0x9gQ?JlMUd2>nC#ke1",
    "l7A>9B{0d0h*^ZJ6svbe5OSq0MHNf1yUfz5P}vJ1>G*022`amELr!UOmCZZ`(W(NE*n#H}pjhN-{e2QDGpL$NopBpN3N",
    "mGxlYDj?u5ap^)5~2!l&Qktfp@Z)-r1nhB)}UyiNHM`ns_r@E>x^<Ld^U^bvPhcm?=Eu2_@nhaLiRy+aoo#fjUk)w@6R",
    "Zn<J0Kf-{a$ojc~#NoEX@Zx~Is9%?^uEZoD=Ia0<4yf$fUeK2$)y2DzWwTykkN&o<fm|_xrk{8eFn>DEyp-3iuR%MDyE",
    "RG=gOBtyG%ClzwnJ}em@<~Y*2zY17E<ZPrtgt@}8boErG>Ie=cuuyd>-`;Ca)y!}z8pug8{6l;!^<`^5ph(7txMDL7vK",
    "+3G{1YZqz?`g;Waet!^8b&x>aX7K1)yDgG3s}co+;~T*H#6gFt^$g*j9qI!mZg{Y~NO9v!Np!z)11RK<A8Z&dHITs^1h",
    "{UDzoDSl-lZe_v%YcevjavH5SV`0%oM(*Cg35Vp>tU2ks!Eu*_A|U^|<-IV3OjmJf?X$baLB-VE1p%*hu3zUi8}M|EAy",
    "a#=YomCUTVx*8UhDMDniOCH6jq62I69e!V2GV{sgF2Oc;;o_iE}+*)g~cB=V<$&U|gtSr)e%O^O+~XzSa@3FV5>DBxQZ",
    "{*`KPf88L1@<+$_5b-{l?iDWAn&^egS!~!|KGxQ~x5Ab+$Q{Hy}2e{b>#s",
]

_ROUTE = json.loads(zlib.decompress(base64.b85decode("".join(_ROUTE_B85_PARTS))))

_PRICE_FLOOR = 1.0
_MARKET_I0 = 10000
_MARKET_PARAMS = {
    "WHEAT": (25, 400, "sqrt", 0.80, "log", 0.20),
    "CARROT": (35, 450, "log", 0.20, "sqrt", 0.70),
    "TOMATO": (60, 200, "linear", 0.40, "sqrt", 0.60),
    "STRAWBERRY": (120, 100, "sqrt", 0.70, "linear", 1.60),
    "MELON": (250, 300, "log", 0.20, "sq", 3.60),
    "EGG": (50, 332, "linear", 0.40, "log", 0.20),
    "MILK": (160, 122, "sqrt", 0.60, "linear", 1.60),
    "WOOL": (200, 105, "log", 0.20, "sq", 3.20),
    "FERTILIZER": (100, 200, "linear", 0.40, "linear", 0.40),
}


def _is_sell(order):
    return (
        isinstance(order, list)
        and len(order) >= 3
        and order[0] == "SELL"
        and order[1] in _MARKET_PARAMS
    )


_SELL_SUFFIX_SUMS: list[dict[str, int]] = [{} for _ in range(len(_ROUTE))]
_current_sums: dict[str, int] = {}
for _t in range(len(_ROUTE) - 1, -1, -1):
    for _order in _ROUTE[_t].get("market") or []:
        if _is_sell(_order) and _order[1] != "WHEAT":
            try:
                _qty = max(0, int(_order[2]))
                _current_sums[_order[1]] = _current_sums.get(_order[1], 0) + _qty
            except (ValueError, TypeError):
                pass
    _SELL_SUFFIX_SUMS[_t] = dict(_current_sums)

# Per-seat repair state. The env builds a fresh process per episode, but a seat
# can still be re-entered, so this resets whenever `step` goes backwards.
_REPAIR: dict = {0: {}, 1: {}}
_REPAIR_SHIFT_STEPS = 8

NO_OP = {"farmer": ["PASS"], "hands": [], "market": []}


def _get(obj, key, default=None):
    if isinstance(obj, dict):
        return obj.get(key, default)
    getter = getattr(obj, "get", None)
    if callable(getter):
        return getter(key, default)
    return getattr(obj, key, default)


def _seat(obs):
    return 1 if int(_get(obs, "player", 0) or 0) == 1 else 0


def _farm(obs, seat):
    farms = list(_get(obs, "farms", []) or [])
    return farms[seat] if seat < len(farms) else {}


def _step_index(obs, config):
    """Turn index. `step` is in the shared observation and is not guaranteed for
    every seat, so fall back to the per-seat clock; the env indexes turns as
    day * turnsPerDay + hour."""
    step = _get(obs, "step")
    if step is not None:
        return int(step)
    per_day = 24
    if config is not None:
        try:
            per_day = int(_get(config, "turnsPerDay", 24) or 24)
        except (TypeError, ValueError):
            per_day = 24
    return int(_get(obs, "day", 0) or 0) * per_day + int(_get(obs, "hour", 0) or 0)


def _copy_action(action):
    action = action or {}
    return {
        "farmer": list(action.get("farmer") or ["PASS"]),
        "hands": [list(h or ["PASS"]) for h in (action.get("hands") or [])],
        "market": [list(o) for o in (action.get("market") or []) if o],
    }


def _align_hands(action, obs):
    expected = len(_get(_farm(obs, _seat(obs)), "hands", []) or [])
    hands = list(action.get("hands") or [])
    if len(hands) < expected:
        hands.extend([["PASS"]] * (expected - len(hands)))
    action["hands"] = [list(h or ["PASS"]) for h in hands[:expected]]
    return action


def _route_at(step):
    if not _ROUTE:
        return {}
    return _ROUTE[min(max(int(step), 0), len(_ROUTE) - 1)] or {}


def _unit_from_route(step, slot):
    trace = _route_at(step)
    if slot == 0:
        return list(trace.get("farmer") or ["PASS"])
    hands = trace.get("hands") or []
    index = slot - 1
    return list(hands[index]) if index < len(hands) else ["PASS"]


def _tile_at(farm, position):
    try:
        return (_get(farm, "tiles", []) or [])[int(position[1])][int(position[0])]
    except (IndexError, TypeError, ValueError):
        return "LOCKED"


def _repair_weeds(obs, action, step):
    """DIG a weed that has appeared under a scripted build/plant, then resume.

    Weeds are the only per-episode randomness that can invalidate a route: a tile
    the route expects to be empty becomes a WEED and every PLANT on it silently
    no-ops for the rest of the game. Repair costs one turn and then replays the
    unit's own trace one step behind for a bounded window.
    """
    seat = _seat(obs)
    state = _REPAIR[seat]
    if step == 0 or step < state.get("last_step", -1):
        state = {"last_step": step, "active": {}}
        _REPAIR[seat] = state
    state["last_step"] = step

    farm = _farm(obs, seat)
    positions = [_get(farm, "farmer"), *list(_get(farm, "hands", []) or [])]
    units = [action.get("farmer") or ["PASS"], *list(action.get("hands") or [])]
    active = state["active"]

    for slot, entry in list(active.items()):
        if slot >= len(units):
            active.pop(slot, None)
            continue
        age = step - entry["start"]
        if age == 1:
            units[slot] = list(entry["intended"])
        elif 2 <= age <= 1 + _REPAIR_SHIFT_STEPS:
            units[slot] = _unit_from_route(step - 1, slot)
        else:
            active.pop(slot, None)

    for slot, (position, intended) in enumerate(zip(positions, units, strict=False)):
        if slot in active or not isinstance(intended, list) or not intended:
            continue
        if intended[0] not in ("PLANT", "BUILD_PASTURE", "BUILD_COOP"):
            continue
        tile = _tile_at(farm, position)
        if not (isinstance(tile, dict) and tile.get("kind") == "WEED"):
            continue
        active[slot] = {"start": step, "intended": list(intended)}
        units[slot] = ["DIG"]

    action["farmer"] = units[0] if units else ["PASS"]
    action["hands"] = units[1:]
    return action


def _shape(name, value):
    value = max(0.0, float(value))
    if name == "sq":
        return value * value
    if name == "sqrt":
        return math.sqrt(value)
    if name == "log":
        return math.log1p(value)
    if name == "log10":
        return math.log10(1.0 + value)
    return value


def _price_at(item, inventory):
    params = _MARKET_PARAMS.get(item)
    if params is None:
        return _PRICE_FLOOR
    base, scale, below_func, below_target, above_func, above_target = params
    if inventory < _MARKET_I0:
        amp = below_target * base / _shape(below_func, scale)
        price = base + amp * _shape(below_func, _MARKET_I0 - inventory)
    else:
        amp = above_target * base / _shape(above_func, scale)
        price = base - amp * _shape(above_func, inventory - _MARKET_I0)
    return max(_PRICE_FLOOR, round(price))


def _impact(obs, order):
    """How much this order moves its own price, times its size."""
    try:
        quantity = max(0, int(order[2]))
    except (TypeError, ValueError):
        return 0.0
    item = str(order[1])
    market = _get(obs, "market", {}) or {}
    inventory = int(_get(_get(market, "inventory", {}) or {}, item, _MARKET_I0) or _MARKET_I0)
    now = _price_at(item, inventory)
    after = _price_at(item, inventory + quantity)
    return float(quantity) * max(0.0, now - after)


def _accelerate_sells(obs, action, step):
    """Sell acceleration and ranking: sell products currently in the shed if they
    are scheduled to be sold later, up to the route's remaining budget for them.
    Ranks all SELL orders by price impact and preserves all non-SELL slots."""
    market = list(action.get("market") or [])
    shed = _get(_get(obs, "private", {}) or {}, "shed", {}) or {}

    new_market = [None] * len(market)
    route_sells = {}

    for i, order in enumerate(market):
        if _is_sell(order):
            item = order[1]
            try:
                qty = max(0, int(order[2]))
                route_sells[item] = route_sells.get(item, 0) + qty
            except (ValueError, TypeError):
                pass
        else:
            new_market[i] = order

    budget = _SELL_SUFFIX_SUMS[step] if step < len(_SELL_SUFFIX_SUMS) else {}
    sells_to_place = []

    items = set(route_sells.keys())
    for item, qty_in_shed in shed.items():
        if item != "WHEAT" and item in budget and qty_in_shed > 0:
            items.add(item)

    for item in items:
        route_qty = route_sells.get(item, 0)
        shed_qty = int(shed.get(item, 0) or 0)
        max_budget = budget.get(item, 0)
        accelerated = min(shed_qty, max_budget) if item != "WHEAT" else 0
        final_qty = max(route_qty, accelerated)

        if final_qty > 0:
            sells_to_place.append(["SELL", item, final_qty])

    if not sells_to_place and len(market) == len(action.get("market") or []):
        return action

    sells_to_place.sort(key=lambda order: (-_impact(obs, order), order[1]))

    sell_idx = 0
    for i in range(len(new_market)):
        if new_market[i] is None:
            if sell_idx < len(sells_to_place):
                # pyrefly: ignore [unsupported-operation]
                new_market[i] = sells_to_place[sell_idx]
                sell_idx += 1

    final_market = [o for o in new_market if o is not None]

    while sell_idx < len(sells_to_place) and len(final_market) < 10:
        # pyrefly: ignore [bad-argument-type]
        final_market.append(sells_to_place[sell_idx])
        sell_idx += 1

    action["market"] = final_market
    return action


def agent(obs, config=None):
    try:
        step = _step_index(obs, config)
        action = _copy_action(_route_at(step))
        action = _repair_weeds(obs, action, step)
        action = _accelerate_sells(obs, action, step)
        return _align_hands(action, obs)
    except Exception:
        try:
            hands = len(_get(_farm(obs, _seat(obs)), "hands", []) or [])
        except Exception:
            hands = 0
        return {"farmer": ["PASS"], "hands": [["PASS"]] * hands, "market": []}
